### PR TITLE
 Fix hydration error in Header.js

### LINKED ISSUE #673: [BUG] The nav bar does not close if the selected nav item is already loaded
### Describe the bug

If we are on a page (say, download page) and we click on nav bar, then on the same page's nav item (here, `download`), the nav bar neither closes nor reloads the page. 

### Steps To Reproduce

1. Go to the official website on any phone.
2. Click on any nav item (download, contact us, or about) 
3. After that page is loaded, re-open the nav bar and click on that same nav item once again.
4. You can see that neither the nav bar closes nor does the page reload.

### Expected Behavior

The nav bar must either close or reload the page. Closing the nav bar is preferable to reduce network usage.

### Operating System

Other

### Browser

Microsoft Edge, Google Chrome, Safari, Brave, Other

### Screenshots

https://github.com/user-attachments/assets/400a768c-e982-41ff-b78e-b70b1016a629

### Additional information

If anyone wants to contribute to this issue, please comment down below.

### Do you want to work on this issue?

No

### PR DESCRIPTION
**Pull request by drippypop**
**Description:**
This PR addresses the hydration error caused by text content mismatch in the server-rendered HTML in the `Header.js` file. The issue was due to nested `<button>` elements. The following changes have been made to resolve this error:

- Removed nested `<button>` elements inside the `NavLink` component.
- Updated the `NavLink` component to use the `Link` component properly.
- Ensured the `setOpen` function is called appropriately to handle toggling the mobile navigation.

**Changes:**
- Updated `Header.js` to remove nested `<button>` elements.
- Improved the structure of the `NavLink` component.

**File(s) Modified:**
- `Website/app/Header.js`

**Before:**
```javascript
function NavLink({ to, children, cn }) {
  return (
    <Link
      scroll={false}
      href={to}
      className={`text-gray-900 hover:text-black ${cn}`}
    >
      <button>{children}</button>
    </Link>
  );
}
```

**After:**
```javascript
function NavLink({ to, children, cn, setOpen }) {
  return (
    <Link
      scroll={false}
      href={to}
      className={`text-gray-900 hover:text-black ${cn}`}
      onClick={() => setOpen(false)}
    >
      {children}
    </Link>
  );
}
```

**Testing:**
- Verified that the hydration error is resolved.
- Tested the mobile navigation to ensure it opens and closes correctly.

**Issue Fixed:**
- Fixes #673 

**Reviewer:**
- Please review the changes and let me know if any further adjustments are needed.

## Summary by CodeRabbit

- **New Features**
	- Enhanced mobile navigation experience with improved link handling.
	- Navigation links now close the mobile menu upon selection.

- **Bug Fixes**
	- Fixed navigation logic to ensure responsive behavior based on user actions.

### CODE REVIEW

**Comment by SaptarshiSarkar12** [comment]
@drippypop Awesome work 👏.
I have verified it works.
What do you think of this review - https://github.com/SaptarshiSarkar12/Drifty/pull/674#discussion_r1787942588?

**Comment by drippypop** [comment]
@SaptarshiSarkar12 fixing it right now

**Comment by SaptarshiSarkar12** [comment]
@drippypop Please fix the reviews and errors by GitHub Advanced Security bot and Coderabbit AI bot.

**Comment by drippypop** [comment]
gosh.. what's going on lol

**Review by drippypop — COMMENTED** [review]
conversations are still there

**Review by SaptarshiSarkar12 — CHANGES_REQUESTED** [review]
@drippypop The fix no longer works 😞. Please check and make the necessary changes. Probably router doesn't work as expected.

**Comment by SaptarshiSarkar12** [comment]
@drippypop As the recent fixes don't work as expected, you can revert to commit https://github.com/SaptarshiSarkar12/Drifty/pull/674/commits/d9a158a12738f3037039633b36446d11535cf6e2
I would accept that change 😁.

**Comment by drippypop** [comment]
@SaptarshiSarkar12 sorry about that! I'll make sure to revert to that

**Comment by SaptarshiSarkar12** [comment]
@drippypop Great 😃👍

**Review by SaptarshiSarkar12 — APPROVED** [review]
@drippypop **Looks good to merge 👍.** 
**Thanks for contributing 🚀 🚀.**
You may join our _Discord server_ - **https://discord.gg/DeT4jXPfkG** to get updates about the project.

**Pull request merged**
