### PR TITLE
Styling[Responsiveness]: Made the site responsive for smaller devices.

### LINKED ISSUE #350: [BUG]: Website is not responsive for devices for 280px - 320px dimension
### Description

The website is not responsive for small devices starting from 280px and also for 320 px.

image
image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by the-shivam-gupta**
## Fixes issue

Fixes #350 

## Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Summary by CodeRabbit

- **Style Updates**
	- Updated heading sizes and class names in the `Contribute` component for improved readability and visual appeal.
	- Enhanced text alignment and size in the `Features` component for a more polished look.
	- Adjusted the layout of the `MainSection` component to fill the screen height for a more immersive experience.
	- Refined image styling with width adjustments and added margins in the global styles for better presentation.

### CODE REVIEW

**Review by SaptarshiSarkar12 — CHANGES_REQUESTED** [review]
- @the-shivam-gupta Please consider reducing the extra spaces in some of the cards (Not all - please check once) :point_down: 
image

- Please add a statement to not display the animation for small devices.
  image
- Please add equal gaps in the left side of the **contribute** button as present in the right side of the **forks** button.
  image

**Comment by the-shivam-gupta** [comment]
okay

**Comment by the-shivam-gupta** [comment]
Ya it would be a nice idea.@SaptarshiSarkar12

**Comment by SaptarshiSarkar12** [comment]
Okay @the-shivam-gupta :+1:

**Comment by the-shivam-gupta** [comment]
Hey @SaptarshiSarkar12, the files are of the same width and height based on the content. Can you plz provide for which screen or browser the problem is occurring:

image

**Comment by the-shivam-gupta** [comment]
Hey should I create a new pull request?

**Comment by SaptarshiSarkar12** [comment]
@the-shivam-gupta Yes, you can. Please keep in mind that you should first update your local git repo and then, work on the task. You must close this PR then :grin:.

**Pull request closed without merging**
