### PR TITLE
Bug Fix : Now can identify default download folder and save file in it.

### PR DESCRIPTION
**Pull request by aryan-upa**
Bug fix for #11

### CODE REVIEW

**Comment by SaptarshiSarkar12** [comment]
is [msc.xml](https://github.com/SaptarshiSarkar12/Drifty/blob/a45db0a3b42ec8c8b0429a6586547832fbf8680d/.idea/misc.xml) a part of the code changes?

**Comment by Anurag-Bharati** [comment]
Hi, I believe [msc. xml](https://github.com/SaptarshiSarkar12/Drifty/blob/a45db0a3b42ec8c8b0429a6586547832fbf8680d/.idea/misc.xml) is not part of the fix. I tried running it on my end (Windows) and it works.

**Comment by SaptarshiSarkar12** [comment]
ok @aryan-upa

**Comment by SaptarshiSarkar12** [comment]
@aryan-upa Please resolve the branch conflicts

**Comment by aryan-upa** [comment]
Hey, sorry for late response. I'm a real noob at this, so can you please explain me what do I have to do, to resolve this conflict. 😶😯

**Comment by aryan-upa** [comment]
Wow! Looks like I really didn't knew what was I doing...

**Pull request closed without merging**
