### PR TITLE
Update instructions to download Drifty

### PR DESCRIPTION
**Pull request by poshi1865**
This takes care of #114

### CODE REVIEW

**Comment by SaptarshiSarkar12** [comment]
@poshi1865 This PR will be merged after the release is made with the update of downloading YouTube videos.

**Comment by poshi1865** [comment]
@SaptarshiSarkar12 Okay cool, so I don't have to do anything as of now to make sure it's mergeable right?

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 Okay cool, so I don't have to do anything as of now to make sure it's mergeable right?

Yes as of now.

**Comment by SaptarshiSarkar12** [comment]
@poshi1865 The user will not need to download yt-dlp manually as I have added that exe file as a part of the jar file as well as the cli exe file and runs quite well.

**Comment by poshi1865** [comment]
@SaptarshiSarkar12 Okay

**Pull request closed without merging**
