### PR TITLE
done with image addition and fixed the borders of the video and allignment of texts 

### PR DESCRIPTION
**Pull request by Shashwat0227**

### CODE REVIEW

**Comment by SaptarshiSarkar12** [comment]
Please add screenshots here. @Shashwat0227

**Comment by Shashwat0227** [comment]
Screenshot (84)
Screenshot (83)
Screenshot (84)
Screenshot (85)

and 1 more img is there , it will change in 3 secs on its own , you can do it by yourself too and fixed the borders of the video

**Comment by Shashwat0227** [comment]
issue #26 solved

**Review by SaptarshiSarkar12 — APPROVED** [review]
LGTM 👍. Thanks for contributing.

**Pull request merged**
