### PR TITLE
updated the contact us heading and button command

### PR DESCRIPTION
**Pull request by anshulsoni4**
please let me know if more changes are required 

issue - #48

### CODE REVIEW

**Comment by anshulsoni4** [comment]
@SaptarshiSarkar12 there is some conflict, can you help me resolve it

**Comment by anshulsoni4** [comment]
@SaptarshiSarkar12 are there any issues ?
like when this will be merged into the main repo

**Comment by SaptarshiSarkar12** [comment]
Please attach screenshots @anshulsoni4

**Comment by anshulsoni4** [comment]
image

Added heading to contact us section and when we click on the contact us button from navbar it redirects us to the contact section.

> > Please attach screenshots @anshulsoni4
> 
> @anshulsoni4 I shall review it after this.

**Comment by SaptarshiSarkar12** [comment]
> image
> 
> Added heading to contact us section and when we click on the contact us button from navbar it redirects us to the contact section.
> 
> > > Please attach screenshots @anshulsoni4
> > 
> > 
> > @anshulsoni4 I shall review it after this.

Please change that. Those icons will be in the footer. **Contact us** links will be my email and link to the issues of my repository and my twitter for DM. Please make a separate section for that and don't link it to the footer

**Comment by anshulsoni4** [comment]
> > image
> > Added heading to contact us section and when we click on the contact us button from navbar it redirects us to the contact section.
> > > > Please attach screenshots @anshulsoni4
> > > 
> > > 
> > > @anshulsoni4 I shall review it after this.
> 
> Please change that. Those icons will be in the footer. **Contact us** links will be my email and link to the issues of my repository and my twitter for DM. Please make a separate section for that and don't link it to the footer

alright I'll change this

**Comment by anshulsoni4** [comment]
image

@SaptarshiSarkar12 please review again

**Review by anshulsoni4 — COMMENTED** [review]
changed the contact us section

**Comment by SaptarshiSarkar12** [comment]
> image
> 
> @SaptarshiSarkar12 please review again

@anshulsoni4 Please change "contribute to Drifty" to "Help And Support" and add support icon.

**Review by anshulsoni4 — COMMENTED** [review]
done changes @SaptarshiSarkar12

**Comment by anshulsoni4** [comment]
image

@SaptarshiSarkar12

**Comment by SaptarshiSarkar12** [comment]
Great!

**Review by SaptarshiSarkar12 — APPROVED** [review]
LGTM 👍 . Thanks for contributing 🚀

**Comment by anshulsoni4** [comment]
> LGTM 👍 . Thanks for contributing 🚀

Thanks a lot ♥

**Pull request merged**
