### PR TITLE
Multiple changes

### PR DESCRIPTION
**Pull request by Waxer59**
# What have I added?
* I have organized the css
* I have added semantic html to the footer
* I fixed the dark mode toggle ( Currently if you activate the bright mode and reload the page the darkmode toggle is inverted and causes you to have errors when changing themes. )
* I have deleted unused css
# Why do I think this will improve the project?
These changes make it easier to locate the css when another contributor wants to support the project.

### CODE REVIEW

**Review by SaptarshiSarkar12 — APPROVED** [review]
LGTM 👍. Thanks for contributing 🚀 🚀

**Comment by SaptarshiSarkar12** [comment]
@Waxer59 Although I have approved and merged it, you need to create an issue and link that to this.

**Comment by SaptarshiSarkar12** [comment]
> @Waxer59 Although I have approved and merged it, you need to create an issue and link that to this.

@Waxer59 Please make an issue. It is important for maintaining the progress of this project.

**Comment by Waxer59** [comment]
Done

**Pull request merged**
