### PR TITLE
Added Custom Matching Scroll Bar

### PR DESCRIPTION
**Pull request by asubodh**

### CODE REVIEW

**Comment by asubodh** [comment]
image

**Comment by SaptarshiSarkar12** [comment]
Please deploy it in the github pages of your repo. It helps me in reviewing.

**Comment by SaptarshiSarkar12** [comment]
Please resolve the conflicts

**Comment by SaptarshiSarkar12** [comment]
@asubodh Please resolve the branch conflicts

**Comment by asubodh** [comment]
Sure!

**Comment by SaptarshiSarkar12** [comment]
@asubodh Ok you may open another PR after pulling the latest changes and making your own changes.

**Pull request closed without merging**
