### PR TITLE
Added Drifty Header Animation

### PR DESCRIPTION
**Pull request by IM-TECHNO**
Hello, I made the Drifty text animation in the header sectiion. 

This is my last minute Hacktoberfest 2022 PR. Please consider. Thank you.

https://user-images.githubusercontent.com/58085092/198817189-1920a009-782a-44f4-98e2-3b45a89988f1.mp4

I have attached a video on how it looks. i'll update even more to even better looking site !. Thanks

### CODE REVIEW

**Comment by SaptarshiSarkar12** [comment]
@IM-TECHNO The animated text goes out of the screen width in mobiles.
Screenshot_2022-10-29-12-03-25

**Comment by SaptarshiSarkar12** [comment]
Also, please create an issue and link that with this PR. @IM-TECHNO

**Comment by IM-TECHNO** [comment]
I have fixed it now, Will make a PR.

**Comment by IM-TECHNO** [comment]
this commit fixes #172

**Comment by IM-TECHNO** [comment]
drifty-mobile

Fixed. I have verified this on Samsung Galaxy F42 as well as Samsung S21.

**Comment by SaptarshiSarkar12** [comment]
@IM-TECHNO Plese make the colour look more prominent in dark mode.
image

**Comment by IM-TECHNO** [comment]
Updated and Fixed the issue. Made the color more prominent.

**Comment by SaptarshiSarkar12** [comment]
@IM-TECHNO Please fix this. The animated text goes out of the screen.
Screenshot_2022-10-29-13-50-36

**Comment by IM-TECHNO** [comment]
May I know what's the resolution of the screen that your using right now ?

**Comment by SaptarshiSarkar12** [comment]
> May I know what's the resolution of the screen that your using right now ?

Don't know about that but the phone model is Samsung Galaxy J2. @IM-TECHNO

**Comment by IM-TECHNO** [comment]
Okay. Thank you for the INFO, addressing the issue,

**Comment by IM-TECHNO** [comment]
Looks like its fixed, kindly check on your device.

**Comment by SaptarshiSarkar12** [comment]
> I fixed the issue, kindly check on your device.

**Comment by SaptarshiSarkar12** [comment]
@IM-TECHNO You can improve the performance. Refer here - https://www.keycdn.com/blog/animation-performance

**Comment by IM-TECHNO** [comment]
Sure. I'll create another PR. Kindly close this one. (hacktoberfest)

**Comment by SaptarshiSarkar12** [comment]
> @IM-TECHNO Please fix this. The animated text goes out of the screen. Screenshot_2022-10-29-13-50-36

Not fixed yet @IM-TECHNO . Please fix it as soon as possible.

**Comment by IM-TECHNO** [comment]
Updated the Whitespacing issue. Please inform if the issue still persists

**Comment by SaptarshiSarkar12** [comment]
Yes it still persists. @IM-TECHNO

**Comment by SaptarshiSarkar12** [comment]
Still persists @IM-TECHNO

**Comment by SaptarshiSarkar12** [comment]
Can you improve the performance? @IM-TECHNO It is very low for mobiles and has decreased a bit for desktops. 
Check here - 
Current - https://pagespeed.web.dev/report?url=https%3A%2F%2Fsaptarshisarkar12.github.io%2FDrifty%2F&form_factor=desktop
with your changes included - https://pagespeed.web.dev/report?url=https%3A%2F%2Fdeploy-preview-171--drifty.netlify.app%2F

**Review by SaptarshiSarkar12 — APPROVED** [review]
LGTM 👍. Thanks for contributing 🚀 🚀.
@IM-TECHNO **Please leave a star ⭐ on this project if you liked contributing to it.**

**Comment by IM-TECHNO** [comment]
Of Course, I loved contributing to Drifty. Starred !

**Comment by SaptarshiSarkar12** [comment]
> Of Course, I loved contributing to Drifty. Starred !

Thank you ❤️ @IM-TECHNO!

**Pull request merged**
