### PR TITLE
Added Download count and Centered all non `ul` elements of release-note

### PR DESCRIPTION
**Pull request by redet-G**
#141 This Adds download count and centers all elements except `ul` ones. @SaptarshiSarkar12 let me know if you find this helpful
image

### CODE REVIEW

**Comment by SaptarshiSarkar12** [comment]
Also add a latest label beside the latest release version @redet-G .

**Comment by redet-G** [comment]
@SaptarshiSarkar12 is this how you want it rendered?https://github.com/SaptarshiSarkar12/Drifty/pull/144/commits/06369051b31e8fa8cf5f8bc4062cfe46dcea4d4b
image

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 is this how you want it rendered?[0636905](https://github.com/SaptarshiSarkar12/Drifty/commit/06369051b31e8fa8cf5f8bc4062cfe46dcea4d4b) image

Yes @redet-G .

**Review by SaptarshiSarkar12 — APPROVED** [review]
LGTM 👍. Thanks for contributing 🚀 🚀 .

**Pull request merged**
