### PR TITLE
Navbar

### PR DESCRIPTION
**Pull request by frypan01**
#88

### CODE REVIEW

**Comment by frypan01** [comment]
I am unable to remove the double sections .please see to it ..they were not present on the local file.

**Comment by SaptarshiSarkar12** [comment]
@frypan01 Please extend this white translucent background to the corner of Drifty icon. 
image

And keep the light and dark mode button as present now - 
image

**Comment by frypan01** [comment]
Please ignore this pull

**Comment by frypan01** [comment]
except logo, is the result fine?

**Comment by SaptarshiSarkar12** [comment]
> except logo, is the result fine?

@frypan01 I need to see this on my laptop. Shall check and inform you when i am free.

**Comment by frypan01** [comment]
please review! I think all work done?

**Comment by SaptarshiSarkar12** [comment]
> @frypan01 Please extend this white translucent background to the corner of Drifty icon. image
> 
> And keep the light and dark mode button as present now - image

@frypan01 keep the light and dark mode button as present now - 
image

**Comment by SaptarshiSarkar12** [comment]
@frypan01 Please revert these changes - 
Before - 

image

image

After - 

image

image

**Comment by SaptarshiSarkar12** [comment]
# @frypan01 **Also, the performance has degraded a lot in mobiles and about 1% for desktops** -
# Before - 

image
image


# After - 

image
image



## Check here: 
### Before - https://pagespeed.web.dev/report?url=https%3A%2F%2Fsaptarshisarkar12.github.io%2FDrifty%2F&form_factor=mobile
### After - https://pagespeed.web.dev/report?url=https%3A%2F%2Fdeploy-preview-106--drifty.netlify.app%2F&form_factor=desktop
</div>

**Comment by frypan01** [comment]
Please see!

**Comment by SaptarshiSarkar12** [comment]
@frypan01 please fix the below problems.
The menu icon is not available for mobiles, hence can't navigate nor can change the light/dark mode.
Screenshot_2022-10-14-20-48-40

The contributor section not loading initially whoch was previously solved.
Screenshot_2022-10-14-20-48-54

The demo button comes over another section.
Screenshot_2022-10-14-20-49-00

**Comment by frypan01** [comment]
Screenshot_20221014-214020

**Comment by SaptarshiSarkar12** [comment]
> Screenshot_20221014-214020

@frypan01 the website seems okay in your phone, but not on my one. What might be the problem? And a solution for this?

**Comment by SaptarshiSarkar12** [comment]
https://github.com/SaptarshiSarkar12/Drifty/pull/106#issuecomment-1279205352
The above image is not visible.

**Comment by frypan01** [comment]
I am checking the problem.....but can't we go with more general screen sizes used.....I think it will work fine?

**Comment by SaptarshiSarkar12** [comment]
Also @frypan01 , the buttons in `all releases` section in download needs to be of the same style as the other buttons in that section.

**Comment by frypan01** [comment]
I am sorry this is my first open source project.....I have annoyed you way too much

**Comment by SaptarshiSarkar12** [comment]
> I am sorry this is my first open source project.....I have annoyed you way too much

@frypan01 It's okay, even I am new to open-source  (just started contributing from 29th May this year). I don't mind that. 😄

**Comment by frypan01** [comment]
well Bangla janen?(informal) please don't mind....I may delete this msg?

**Comment by SaptarshiSarkar12** [comment]
> well Bangla janen?(informal) please don't mind....I may delete this msg?

Yes

**Comment by frypan01** [comment]
Hey ! this is M. Banerjee!!

**Comment by SaptarshiSarkar12** [comment]
> Hey ! this is M. Banerjee!!

Ok, I'm Saptarshi Sarkar.

**Comment by frypan01** [comment]
Please review once again?

**Comment by SaptarshiSarkar12** [comment]
> Please review once again? I think all is set

@frypan01 the menu icon not visible.

**Comment by SaptarshiSarkar12** [comment]
> Please review once again? I think all is set

@frypan01 the menu icon is not visible. 
Screenshot_2022-10-15-07-44-46

**Comment by SaptarshiSarkar12** [comment]
Sorry, Closed the Pull Request by mistake. @frypan01

**Comment by frypan01** [comment]
I am unable to do it....if you can specify the screen size?

**Comment by SaptarshiSarkar12** [comment]
> I am unable to do it....if you can specify the screen size? now check....because now its working in all mobile size in google tools... maybe this is happening because icons are too big for such small screen or unable to load

@frypan01 It's still not working on my device.
Please check how the current website automatically sets the screen size width and all the icons are in their proper location.

**Comment by frypan01** [comment]
Please check again if it persists....

**Comment by SaptarshiSarkar12** [comment]
> Please check again if it persists....

@frypan01 Yes it persists. You can rebase your branch and then , make only the required changes (although it's scary).
Screenshot_2022-10-15-22-14-55

**Comment by frypan01** [comment]
If you don't mind......we can create a new issue and ask for help

**Comment by frypan01** [comment]
I messed up!

**Comment by SaptarshiSarkar12** [comment]
> I messed up!

You can create a new branch and open a PR from that after making the required changes. @frypan01

**Pull request closed without merging**
