### PR TITLE
Added Github stars and forks count in website. closes issue #82

### PR DESCRIPTION
**Pull request by Akshatjaiswal5**
Please link this pr to issue #82 if not already.
Added stars and fork count, other changes are due to my formatter.
Please review and merge these changes before 30oct, I want them counted in Hacktoberfest.
Thank you.

### CODE REVIEW

**Comment by SaptarshiSarkar12** [comment]
@Akshatjaiswal5 Please keep the stars and forks in the more info section below the text and beside `contribute to drifty` button.
image

**Comment by SaptarshiSarkar12** [comment]
> @Akshatjaiswal5 Please keep the stars and forks in the more info section below the text and beside `contribute to drifty` button. image

@Akshatjaiswal5 please make the changes.

**Comment by Akshatjaiswal5** [comment]
> > @Akshatjaiswal5 Please keep the stars and forks in the more info section below the text and beside `contribute to drifty` button. image
> 
> @Akshatjaiswal5 please make the changes.

Done

**Comment by SaptarshiSarkar12** [comment]
@Akshatjaiswal5 Please fix this for mobiles. The buttons moved out of the screen width.
Screenshot_2022-10-26-17-09-20

**Comment by Akshatjaiswal5** [comment]
Please check it now

**Comment by SaptarshiSarkar12** [comment]
> Please check it now

Please add link to [stargazers](https://github.com/SaptarshiSarkar12/Drifty/stargazers) and [forks](https://github.com/SaptarshiSarkar12/Drifty/network/members) link to the respective buttons.
@Akshatjaiswal5

**Comment by Akshatjaiswal5** [comment]
> > Please check it now
> 
> Please add link to [stargazers](https://github.com/SaptarshiSarkar12/Drifty/stargazers) and [forks](https://github.com/SaptarshiSarkar12/Drifty/network/members) link to the respective buttons. @Akshatjaiswal5

Done

**Comment by SaptarshiSarkar12** [comment]
@Akshatjaiswal5 please resolve the conflicts. Then, i shall merge this PR.

**Comment by Akshatjaiswal5** [comment]
> @Akshatjaiswal5 please resolve the conflicts. Then, i shall merge this PR.

Done

**Comment by SaptarshiSarkar12** [comment]
> > @Akshatjaiswal5 please resolve the conflicts. Then, i shall merge this PR.
> 
> Done

Great ! @Akshatjaiswal5

**Review by SaptarshiSarkar12 — APPROVED** [review]
LGTM 👍. Thanks for contributing 🚀 🚀 
@Akshatjaiswal5 **Please leave a star ⭐ on this project if you liked contributing to it. You may join my Discord server for the project's Discussions - https://discord.gg/DeT4jXPfkG**

**Pull request merged**
