### PR TITLE
Changes made in README of the Website

### PR DESCRIPTION
**Pull request by sathvik-ng-07**
I have submitted a pull request that addresses the documentation improvements for Drifty as discussed in the issue #273 

**Changes Proposed:**
- [ ] Created separate Markdown files for each documentation section (Quickstart, Getting Started, Contributing, FAQ, and Troubleshooting).
- [ ] Populated these files with clear and detailed content, including examples and code snippets where necessary.
- [ ] Updated the main README file to link to the newly created documentation files.
Thank you for your time and consideration. I look forward to your feedback and the opportunity to improve the documentation for Drifty.

### CODE REVIEW

**Comment by SaptarshiSarkar12** [comment]
@sathvik-ng-07 You need to make changes in the Website. A docs section should be made in the Website which will have the subsections as said. You are not supposed to add more README files.

**Comment by SaptarshiSarkar12** [comment]
You can see this [docs](https://nextjs.org/docs/app/building-your-application/configuring/mdx) on how to make the website render markdown contents

**Comment by sathvik-ng-07** [comment]
> @sathvik-ng-07 You need to make changes in the Website. A docs section should be made in the Website which will have the subsections as said. You are not supposed to add more README files.
oh alright. seems like i misunderstood the issue. will check it out

**Comment by SaptarshiSarkar12** [comment]
It's okay, no problem. You can make the changes to the website via this PR (if you wish, there is no need to create another PR).

**Pull request closed without merging**
