### PR TITLE
footers added

### LINKED ISSUE #9: [FEATURE] can add social handles in the footer
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by Shashwat0227**
hey created the footers
Fixes #9

### CODE REVIEW

**Comment by SaptarshiSarkar12** [comment]
@Shashwat0227 please link the issue.

**Comment by Shashwat0227** [comment]
i commented there , i dont know how to link that

**Comment by SaptarshiSarkar12** [comment]
Ok, i have linked that.
@Shashwat0227 Please add a screenshot

**Comment by Shashwat0227** [comment]
footers1final
check it out

**Comment by SaptarshiSarkar12** [comment]
> footers1final check it out

It looks awesome ! Great work.

**Comment by Shashwat0227** [comment]
just accept it , it will be counted then

**Review by SaptarshiSarkar12 — APPROVED** [review]
LGTM 👍 . Thanks for contributing.

**Pull request merged**
