### PR TITLE
Create LICENSE.md

### PR DESCRIPTION
**Pull request by rahulkarda**

### CODE REVIEW

**Comment by SaptarshiSarkar12** [comment]
@rahulkarda License file is already present in the repository.

**Comment by rahulkarda** [comment]
Sorry for the mistake.

**Comment by SaptarshiSarkar12** [comment]
It's okay @rahulkarda. You may open any other issues.

**Comment by rahulkarda** [comment]
> It's okay @rahulkarda. You may open any other issues.

Should I add meta tags like description, author in index.html? Sorry for asking but I'm new to this.

**Comment by SaptarshiSarkar12** [comment]
> > It's okay @rahulkarda. You may open any other issues.
> 
> Should I add meta tags like description, author in index.html? Sorry for asking but I'm new to this.

You may do so, but #8 and #9 are in progress.

**Pull request closed without merging**
