### PR TITLE
The basic site

### PR DESCRIPTION
**Pull request by Shashwat0227**
hey i created the basic site , now will add dark mode and footers also ,

### CODE REVIEW

**Comment by Shashwat0227** [comment]
hey can you accept the pull request so i can proceed further

**Comment by Shashwat0227** [comment]
hey can you accept the pull request so i can proceed further

**Review by SaptarshiSarkar12 — APPROVED** [review]
LGTM 👍. Thanks for contributing 🚀🚀

**Comment by Shashwat0227** [comment]
hey but i fixed 2 issues under single PR , so it will be counted as 1?can you do something about it ? cuz i added dark mode also and made site also

**Comment by SaptarshiSarkar12** [comment]
Yes @Shashwat0227 , it will be counted as 1.

**Comment by Shashwat0227** [comment]
okay i will add footers and then again pull the request

**Comment by SaptarshiSarkar12** [comment]
ok @Shashwat0227

**Comment by PinetheApple** [comment]
hello. I'm looking to contribute to this.

Noticed that the text on the site in light mode is really hard to see and that it's not really responsive. Let me know if someone's working on this already or if I can be of help here.
image

**Comment by SaptarshiSarkar12** [comment]
> hello. I'm looking to contribute to this.
> 
> Noticed that the text on the site in light mode is really hard to see and that it's not really responsive. Let me know if someone's working on this already or if I can be of help here. image

Yes, @Shashwat0227 is working on the website and it will be completed by today. So, @PinetheApple, you may open an issue for the changes you want to bring in that, after he completes.

**Comment by PinetheApple** [comment]
Alright then :+1:

**Pull request merged**
