### PR TITLE
New nav bar

### PR DESCRIPTION
**Pull request by frypan01**
#106  #88

### CODE REVIEW

**Comment by frypan01** [comment]
It's still not there...

**Comment by SaptarshiSarkar12** [comment]
> It's still not there...

@frypan01 Delete your fork repo, your local repo. Then, fork my repo again, make **only** the required changes in your local repo and open the PR once again. That's the best option I could think of. 
**Please make only the required changes.**

**Comment by frypan01** [comment]
Ok, but I need some time ...I have exam tomorrow

**Comment by SaptarshiSarkar12** [comment]
> Ok, but I need some time ...I have exam tomorrow

Ok @frypan01 . Do the work when you are free.

**Pull request closed without merging**
