### PR TITLE
Overflow of Github buttons fixed

### PR DESCRIPTION
**Pull request by itshypon**
When switched to IPad, buttons of github div starts overflowing. 
2 reasons for occurence of recent opened issue (Github button and animation overflow)
One is fixed, one is remaining.

Before
image

After
image

### CODE REVIEW

**Comment by SaptarshiSarkar12** [comment]
The deploy preview link is available here - https://deploy-preview-205--drifty.netlify.app/

**Comment by SaptarshiSarkar12** [comment]
Hey @itshypon, the 2nd issue causing the overflow has been solved by PR #206 . I am reviewing your changes for resolving the 1st issue for the overflow.

**Review by SaptarshiSarkar12 — APPROVED** [review]
@itshypon **Looks good to merge 👍.** 
**Thanks for contributing 🚀 🚀.**
You may join our _Discord server_ - **https://discord.gg/DeT4jXPfkG** to get updates about the project.

**Comment by itshypon** [comment]
@SaptarshiSarkar12 Yeah, thanks ! I'm already in discord server since october as I also created ASCII logo of Drifty when it was in early stage in Hacktoberfest.

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 Yeah, thanks ! I'm already in discord server since october as I also created ASCII logo of Drifty when it was in early stage in Hacktoberfest.

Yeah I know @itshypon ! You were the first person who has a great contribution to the look and feel of the Drifty CLI at present. 
The comment that I gave was a saved reply, so I forgot to remove the last line. Please don't mind.

**Pull request merged**
