### PR TITLE
About page created using Readme.md file

### PR DESCRIPTION
**Pull request by anantnipunge**
i have created about page as a new `about.html` file. you can check here and share your reviews. if you found it good then please merge this PR. later i will improve it using another issue. @SaptarshiSarkar12

### CODE REVIEW

**Comment by anantnipunge** [comment]
Hello did you like the page i have created? Tell me to update something else please merge this PR. @SaptarshiSarkar12

**Review by SaptarshiSarkar12 — APPROVED** [review]
LGTM 👍. Thanks for contributing 🚀 🚀.

**Comment by SaptarshiSarkar12** [comment]
> Hello did you like the page i have created? Tell me to update something else please merge this PR. @SaptarshiSarkar12

It's great, just I have made some changes as required. @anantnipunge

**Comment by anantnipunge** [comment]
Okay thanks @SaptarshiSarkar12  . I willing to contribute more in your project. I'm learning lot of things while doing this project.

**Comment by SaptarshiSarkar12** [comment]
> Okay thanks @SaptarshiSarkar12 . I'm willing to contribute more in your project. I'm learning lot of things while doing this project.
> 
> So if you can tell me by your end Where to contribute in your project, it will be a great to Start ! @SaptarshiSarkar12

Welcome @anantnipunge!
It's great that you want to contribute more and help the project grow, I highly appreciate you for this.
I have some ideas in mind like creating separate web pages for each nav elements. You may work on it after creating the issue addressing the feature.
Also, have you learned java?

**Comment by anantnipunge** [comment]
Yes i have mostly worked on React.js . You can please checkout my github profile. And i have learned java but not for developement but if your project requires development java i can quickly learn some advance concept and also  i'm focused on competitive programming and web development. I used yo write code in java only.

**Comment by anantnipunge** [comment]
And yeah i wil work on creating separate web pages for each nav elements. @SaptarshiSarkar12

**Comment by anantnipunge** [comment]
Btw if you don't mind can i message you in discord in personal

**Comment by SaptarshiSarkar12** [comment]
> Btw if you don't mind can i message you in discord in personal

Yes, you can @anantnipunge .

**Comment by SaptarshiSarkar12** [comment]
> Yes i have mostly worked on React.js . You can please checkout my github profile. And yes have learned java and it's almost 8 months working on java. but not for developement but if your project requires development java i can quickly learn some advance concept and also i'm focused on competitive programming and web development. I used yo write code in java only. @SaptarshiSarkar12

That's great @anantnipunge ! 👏

**Pull request merged**
