### PR TITLE
Adds See More option for releases to see release note #141

### PR DESCRIPTION
**Pull request by redet-G**

### CODE REVIEW

**Comment by redet-G** [comment]
#141

**Comment by SaptarshiSarkar12** [comment]
@redet-G the text goes out of the screen size and some part of the release notes is not rendered (Here you can add `Show More` option in case of lengthy release notes)

Screenshot_2022-10-22-21-54-57
Screenshot_2022-10-22-21-54-47

**Comment by SaptarshiSarkar12** [comment]
@redet-G Also change `see More` to `Learn More`

**Comment by redet-G** [comment]
@SaptarshiSarkar12 That was a great catch.
I have fixed the width issues (https://github.com/SaptarshiSarkar12/Drifty/pull/142/commits/e9708d04f7976bfb896e3f2658c4fe599abd5b2a) and calculated the height dynamically (https://github.com/SaptarshiSarkar12/Drifty/pull/142/commits/7548096f172e2669a42f65a7104d21eb3d67821c).

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 That was a great catch. I have fixed the width issues ([e9708d0](https://github.com/SaptarshiSarkar12/Drifty/commit/e9708d04f7976bfb896e3f2658c4fe599abd5b2a)) and calculated the height dynamically ([7548096](https://github.com/SaptarshiSarkar12/Drifty/commit/7548096f172e2669a42f65a7104d21eb3d67821c)).

@redet-G Please align this part in the center of the screen.
image

**Comment by SaptarshiSarkar12** [comment]
> > @SaptarshiSarkar12 That was a great catch. I have fixed the width issues ([e9708d0](https://github.com/SaptarshiSarkar12/Drifty/commit/e9708d04f7976bfb896e3f2658c4fe599abd5b2a)) and calculated the height dynamically ([7548096](https://github.com/SaptarshiSarkar12/Drifty/commit/7548096f172e2669a42f65a7104d21eb3d67821c)).
> 
> @redet-G Please align this part in the center of the screen. image

I mean the text.

**Comment by SaptarshiSarkar12** [comment]
@redet-G Please fix this by aligning this text in the center.

**Comment by SaptarshiSarkar12** [comment]
Sorry @redet-G , closed this by mistake!

**Comment by SaptarshiSarkar12** [comment]
Please align the release notes in the center @redet-G !

**Comment by redet-G** [comment]
It does not look great when the release note is centered.
image
After centering the whole thing
image

**Comment by SaptarshiSarkar12** [comment]
ok then @redet-G .

**Comment by redet-G** [comment]
or We could center all  none UL elements. Like this.
image

**Review by SaptarshiSarkar12 — APPROVED** [review]
LGTM 👍. Thanks for contributing 🚀 🚀.

**Pull request merged**
