### PR TITLE
Added link for about section

### PR DESCRIPTION
**Pull request by Kamlesh72**

### CODE REVIEW

**Comment by SaptarshiSarkar12** [comment]
@Kamlesh72 please add my github readme as about , along with my github avatar

**Comment by Kamlesh72** [comment]
Should I also change position of About in navbar and About for content?
Like the About section should be below Download section.

**Comment by SaptarshiSarkar12** [comment]
> Should I also change position of About in navbar and About for content? Like the About section should be below Download section.

Yes @Kamlesh72 .

**Comment by SaptarshiSarkar12** [comment]
> Should I also change position of About in navbar and About for content? Like the About section should be below Download section.

Have you completed the work? @Kamlesh72

**Comment by Kamlesh72** [comment]
Not yet. But I will do it by tomorrow morning.

**Comment by SaptarshiSarkar12** [comment]
> Not yet. But I will do it by tomorrow morning.

@Kamlesh72 ok

**Comment by Kamlesh72** [comment]
Hey @SaptarshiSarkar12 , Sorry to tell but I would not be able to complete it on time. Kindly assign it to someone else.

**Comment by SaptarshiSarkar12** [comment]
> Hey @SaptarshiSarkar12 , Sorry to tell but I would not be able to complete it on time. Kindly assign it to someone else.

Ok @Kamlesh72 .

**Pull request closed without merging**
