### PR TITLE
Added accurate color coding fill-in effect to social media icons in the footer.

### PR DESCRIPTION
**Pull request by codedmachine111**
Hello @SaptarshiSarkar12 . I have added a decent styling to the footer icons by adding a fill-in effect on hover with accurate color codes. Kindly review my PR.

### CODE REVIEW

**Comment by SaptarshiSarkar12** [comment]
@codedmachine111 there are some performance issues, please check at https://pagespeed.web.dev

**Comment by codedmachine111** [comment]
Hello @SaptarshiSarkar12 . I looked into it and all i have to say is that i just changed the hover effect with some css (you can view my commits). Nothing major was changed. As per the website, the issues taking up most of the time are :-
Not Properly size images
5.1 s

I apologize, but i do not think my code has major changes to cause performance issues. Kindly review it again. Thankyou.

**Comment by SaptarshiSarkar12** [comment]
> Hello @SaptarshiSarkar12 . I looked into it and all i have to say is that i just changed the hover effect with some css (you can view my commits). Nothing major was changed. As per the website, the issues taking up most of the time are :- Not Properly size images 5.1 s
> 
> I apologize, but i do not think my code has major changes to cause performance issues. Kindly review it again and i would love to change my code or add something new.Thankyou.

Ok @codedmachine111 . Please create an issue at first and link that to this PR.

**Review by SaptarshiSarkar12 — APPROVED** [review]
LGTM 👍 . Thanks for contributing. Please leave a star on this project if you liked it. @codedmachine111 . Please create an issue although i am going to merge it.

**Pull request merged**
