### PR TITLE
Added Multithreaded downloading support #145

### PR DESCRIPTION
**Pull request by redet-G**
- Still needs progress bar support

### CODE REVIEW

**Comment by SaptarshiSarkar12** [comment]
Please add progress bar support and then let me know when you are done. @redet-G

**Comment by SaptarshiSarkar12** [comment]
@redet-G You can [join my Discord server](https://discord.gg/DeT4jXPfkG) for the project's discussions .

**Comment by redet-G** [comment]
@SaptarshiSarkar12 Progress bar support for multithreaded downloading is now complete.

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 Progress bar support for multithreaded downloading is now complete.

Ok @redet-G shall check and inform you when I am done. Thanks .

**Comment by SaptarshiSarkar12** [comment]
@redet-G The program freezes [see image] - 
image

**Comment by redet-G** [comment]
Can you be more specific as to how it could be reproduced?  Where the head is right now (commit id)?
The file size is only 14 MB. Multithreading is currently enabled for files above 50 MB.  You can modify  `FileDownloader.threadingThreshold` for testing. 

image

Here is a screenshot of downloading a file above 50MB.
image

**Comment by SaptarshiSarkar12** [comment]
> Can you be more specific as to how it could be reproduced? Where the head is right now (commit id)? The file size is only 14 MB. Multithreading is currently enabled for files above 50 MB. You can modify `FileDownloader.threadingThreshold` for testing.
> 
> image
> 
> Here is a screenshot of downloading a file above 50MB. image @SaptarshiSarkar12

It seems okay from your end. Let me try it again tonight, shall let you know then @redet-G

**Review by SaptarshiSarkar12 — APPROVED** [review]
LGTM 👍. Thanks for contributing 🚀 🚀

**Pull request merged**
