### PR TITLE
About section created 

### PR DESCRIPTION
**Pull request by anantnipunge**
**This is for issue #127** . i have created `about` section in the website. **please merge this PR**. if you want to add more stuff in `about` please tell me to update it . @SaptarshiSarkar12 

**_here you can see the changes:_**

image

image

image

image

### CODE REVIEW

**Comment by SaptarshiSarkar12** [comment]
@anantnipunge Please make the colour more prominent.
image

**Comment by anantnipunge** [comment]
Okay .

**Comment by SaptarshiSarkar12** [comment]
Yeah, it looks good. But it will be better if you can keep the whole readme of my profile in the about section. What do you say? @anantnipunge

**Comment by anantnipunge** [comment]
Yeah it's definitely a good idea, but i think it will be a very bigger section having long content. And it may look weird. So can we just write 5 to 6 steps in about section to download the file ? So that user would get more convenience to download the file ?

**Comment by SaptarshiSarkar12** [comment]
> Yeah it's definitely a good idea, but i think it will be a very bigger section having long content. And it may look weird. So can we just write 5 to 6 steps in about section to download the file ? So that user would get more convenience to download the file ?

You can create a new web page for the about section (something like about.html). @anantnipunge

**Comment by anantnipunge** [comment]
Okay @SaptarshiSarkar12 

Please mention the readme file . i'm bit confuse about readme file

Also can you please merge this PR. and after that i will create new web page for the about section. And will delete this section from `index.html`.

**Comment by SaptarshiSarkar12** [comment]
> Okay @SaptarshiSarkar12
> 
> Please mention the readme file . i'm bit confuse about readme file
> 
> Also can you please merge this PR. and after that i will create new web page for the about section. And will delete this section from `index.html`.

`Readme file` - https://github.com/SaptarshiSarkar12/SaptarshiSarkar12/blob/main/README.md
ok, please make the changes as soon as possible. @anantnipunge

**Comment by anantnipunge** [comment]
Aare you going to merge this PR?

**Comment by SaptarshiSarkar12** [comment]
> Aare you going to merge this PR?@SaptarshiSarkar12

Yes, I'm doing a bit of editing on the about description. @anantnipunge

**Comment by anantnipunge** [comment]
okay i have created new about.html page will submit it soon. working on good designing and adding some buttons there.
@SaptarshiSarkar12

**Review by SaptarshiSarkar12 — APPROVED** [review]
LGTM 👍. Thanks for contributing 🚀 🚀.
@anantnipunge **Please leave a star ⭐ on this project if you liked contributing to it and you may join our Discord server - https://discord.gg/DeT4jXPfkG**

**Comment by SaptarshiSarkar12** [comment]
> okay i have created new about.html page working on it, will submit it soon. working on good designing and adding some buttons there. @SaptarshiSarkar12
> 
> see:
> 
> image

Please keep the header and footer same for the webpage, just change the body part. @anantnipunge

**Comment by anantnipunge** [comment]
> > okay i have created new about.html page working on it, will submit it soon. working on good designing and adding some buttons there. @SaptarshiSarkar12
> > see:
> > image
> 
> Please keep the header and footer same for the webpage, just change the body part. @anantnipunge

okay thanks working on it

**Comment by anantnipunge** [comment]
i'm creating new issue for this please assign me this issue @SaptarshiSarkar12

**Pull request merged**
