### PR TITLE
NavBar modiifed

### PR DESCRIPTION
**Pull request by frypan01**

### CODE REVIEW

**Comment by frypan01** [comment]
How to undo this?

**Comment by SaptarshiSarkar12** [comment]
> How to undo this?

Which one?

**Comment by frypan01** [comment]
this one!! i did it  by mistake

**Comment by SaptarshiSarkar12** [comment]
> this one!! i did it by mistake

The PR?

**Comment by frypan01** [comment]
Maybe yes , its showing Resolve conflicts? how to do that?

**Comment by SaptarshiSarkar12** [comment]
> Maybe yes , its showing Resolve conflicts? how to do that?

I am resolving that. Please wait.

**Comment by SaptarshiSarkar12** [comment]
@frypan01 Please deploy your changes in your repo. Refer here : #74

**Comment by frypan01** [comment]
#74

**Comment by SaptarshiSarkar12** [comment]
@frypan01 What changes have you brought? I can't find any of those changes in the website.

image

**Comment by SaptarshiSarkar12** [comment]
Sorry @frypan01 , the feature needs some changes and it will slow down the performance. So, please take a note of that. 

image

**Comment by frypan01** [comment]
Yeah! Anything specific you would like me to change, like any style  or  color  in mind.

**Comment by SaptarshiSarkar12** [comment]
> Yeah! Anything specific you would like me to change, like any style or color in mind.

No, it seems good as of now.

**Comment by SaptarshiSarkar12** [comment]
> > Yeah! Anything specific you would like me to change, like any style or color in mind.
> 
> No, it seems good as of now.

What do you think?

**Comment by frypan01** [comment]
we can remove the neon buttons? and let Home ..... be simple text , reduce the length and width of navbar, make the nav bit slim? and make it entirely with tailwind?

**Comment by SaptarshiSarkar12** [comment]
> we can remove the neon buttons? and let Home ..... be simple text , reduce the length and width of navbar, make the nav bit slim? and make it entirely with tailwind?

@frypan01 Yes that's a great idea! Closing this PR. Please pull the latest changes, then make the changes you want to bring and then open another PR.

**Pull request closed without merging**
