### PR TITLE
Add CLS when downloading next file

### LINKED ISSUE #39: [FEATURE] Add a CLS function on Java using CMD
**Description**
In the else if statement adding a cls to clear screen on command line

### PR DESCRIPTION
**Pull request by Fonta22**
Fixes #39 

Now the banner is printed from a function called `printBanner`, which clears the screen and after prints the banner.
This function is called when the program starts and when the user wants to download one file more.

If you don't want it to clear the screen on start, please say it to me and I'll change it so it will only clear the screen when the user wants to download one more file. 👍🏻

### CODE REVIEW

**Comment by SaptarshiSarkar12** [comment]
> ```java
> ```java
> 
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

Ok @Fonta22 , let me check once. If it works.
You may attach a video showing the clearing of the screen.

**Comment by Fonta22** [comment]
Alright @SaptarshiSarkar12

**Comment by Fonta22** [comment]
@SaptarshiSarkar12 Demo video:

https://user-images.githubusercontent.com/61181201/193624981-8aca88d7-3b64-47a9-a781-e6f029c86ae8.mp4

**Comment by SaptarshiSarkar12** [comment]
ok @Fonta22. Approving it. Nice work! Thanks for contributing!

**Comment by SaptarshiSarkar12** [comment]
Oh no, @Fonta22 Please resolve the branch conflicts

**Comment by Fonta22** [comment]
> ok @Fonta22. Approving it. Nice work! Thanks for contributing!

Np! 👍🏻

**Pull request merged**
