### PR TITLE
update(readme.md): organized badges

### PR DESCRIPTION
**Pull request by BoseSj**
## Description 
Moved and organized the badges in README.md.

## Output
image

### CODE REVIEW

**Review by SaptarshiSarkar12 — APPROVED** [review]
LGTM. Thanks for contributing. 👍

**Comment by SaptarshiSarkar12** [comment]
@BoseSj Although I have merged it, you need to create an issue and link that with this PR.

**Comment by BoseSj** [comment]
Okay, cool! I will be creating one😄

**Comment by BoseSj** [comment]
Solves issue #81

**Pull request merged**
