### PR TITLE
separate web-pages created for each nav-bar elements

### PR DESCRIPTION
**Pull request by anantnipunge**
here i have created separate webpages for each navbar items.

please review this: [https://deploy-preview-188--drifty.netlify.app/](url)

### CODE REVIEW

**Comment by anantnipunge** [comment]
i think still we need to work on each nav elements like adding more features.

**Comment by SaptarshiSarkar12** [comment]
@anantnipunge Please resolve the branch conflicts.

**Comment by SaptarshiSarkar12** [comment]
Also, please make the animation as it is now. @anantnipunge 
image

**Comment by anantnipunge** [comment]
Ok @SaptarshiSarkar12

**Comment by SaptarshiSarkar12** [comment]
@anantnipunge Please resolve the branch conflicts and also fix this bug. The color of dark and light mode is same for more info section.
image

**Comment by anantnipunge** [comment]
is there any tool in github or maybe external to see where this conflicts exists in the file? @SaptarshiSarkar12  i'm unable to find conflicts.

**Comment by anantnipunge** [comment]
i have deleted `about.css` file, but still its showing it's a conflict file.

**Comment by SaptarshiSarkar12** [comment]
> is there any tool in github or maybe external to see where this conflicts exists in the file? @SaptarshiSarkar12 i'm unable to find conflicts.

Sorry @anantnipunge I was busy, so I couldn't reply.
You can refer this : https://stackoverflow.com/a/49382772/19187952
This might work.

**Comment by SaptarshiSarkar12** [comment]
> i have deleted `about.css` file, but still its showing it's a conflict file.
> 
> i think it will take time to resolve conflicts. once done, i will submit it soon.

at first you delete the conflicting files, pull the latest changes in your local repo and then, make the required changes. This should work.

**Comment by anantnipunge** [comment]
Ok 😊

**Comment by anantnipunge** [comment]
hello @SaptarshiSarkar12 please review the changes

**Comment by SaptarshiSarkar12** [comment]
> hello @SaptarshiSarkar12 please review the changes

Please fix this for mobiles.
Screenshot_2022-11-03-15-16-58

**Comment by anantnipunge** [comment]
https://deploy-preview-188--drifty.netlify.app/index.html#contact

**Comment by SaptarshiSarkar12** [comment]
Please see if you can fix this bug @anantnipunge .

**Comment by anantnipunge** [comment]
can you please check it now in your mobile. i made changes and reviewed for 4 to 5 devices on chrome, it's working well  and already it was also working well. please review this @SaptarshiSarkar12

**Comment by SaptarshiSarkar12** [comment]
@anantnipunge Now, after adding 5 `</br>` tags, the buttons no more coincide with the footer part in my mobile. I shall check on my laptop and inform you if it works fine. Also, I need to check other pages as well. I shall inform you then.

**Comment by SaptarshiSarkar12** [comment]
@anantnipunge Please fix this bug. Change the background colour as the dark mode button is not properly visible or you can change the color of the dark mode button, and add `Download Here...` as it is now. Also, make `All releases` option as a `span` as the website length will increase as the number of releases increases.
image

**Comment by anantnipunge** [comment]
Sure i will submit it soon working on it

**Comment by anantnipunge** [comment]
please check this do you like this?? @SaptarshiSarkar12

**Comment by SaptarshiSarkar12** [comment]
@anantnipunge The icon size in bout section is not the same s in the other sections. also, change the moon color to black / dark grey and keep the sun as tomato (it looks nice). also contribute page does not have distinct background colours for dark and light mode. also make all releases a span like Learn More.

Icon size in bout pages:
image
Icon size in other pages:
image

Contribute page in dark mode:
image
Contribute page in light mode:
image

**Comment by anantnipunge** [comment]
Ya okay

**Comment by anantnipunge** [comment]
made required changes. plz review this.
@SaptarshiSarkar12

**Comment by anantnipunge** [comment]
working on darkmode toggle button to change color according to dark and light

**Comment by SaptarshiSarkar12** [comment]
@anantnipunge Please remove the shadow for light mode in contribute page. Also change the button colour for light mode (you may keep it white). 
image
image

### Please make this as span. It will display the releases only when it is clicked.
image

**Comment by anantnipunge** [comment]
ok

**Comment by SaptarshiSarkar12** [comment]
> ok

How far is the work completed @anantnipunge ?

**Comment by anantnipunge** [comment]
Working on it. My exam and submission is there i will submit it soon.

**Comment by anantnipunge** [comment]
@SaptarshiSarkar12

**Comment by SaptarshiSarkar12** [comment]
> Working on it. My exam and submission is there i will submit it soon.

Ok you can push the changes after you are done. @anantnipunge

**Comment by anantnipunge** [comment]
Sure 😊 no worries.

**Comment by anantnipunge** [comment]
hello @SaptarshiSarkar12 , shadow is removed but i'm unable to provide required feature to the all release section.

**Comment by SaptarshiSarkar12** [comment]
> hello @SaptarshiSarkar12 , shadow is removed but i'm unable to provide required feature to the all release section.
> 
> i think release section code is written somewhere else, i'm not getting that.

Ok shall check after my laptop is fixed. @anantnipunge . It might take a week.

**Comment by anantnipunge** [comment]
Ya ok @SaptarshiSarkar12 . I will be available for other contribution anytime. 😊

**Comment by SaptarshiSarkar12** [comment]
> Ya ok @SaptarshiSarkar12 . I will be available for other contribution anytime. 😊

👍

**Comment by SaptarshiSarkar12** [comment]
> hello @SaptarshiSarkar12 , shadow is removed but i'm unable to provide required feature to the all release section.
> 
> i think release section code is written somewhere else, i'm not getting that.

@anantnipunge Yes, the releases section code is written in script.js file starting from line 161. Please check if you can make the `All releases` section just like `Learn More` text.

**Comment by anantnipunge** [comment]
Ok i will see.

**Comment by SaptarshiSarkar12** [comment]
> Ok i will see.

Have you seen it @anantnipunge ?

**Comment by SaptarshiSarkar12** [comment]
> Sorry for the late. But till friday i'm so busy as there is my exam going on. Till the saturday i will update you for sure.

Okay 👍.

**Comment by anantnipunge** [comment]
Thanks for understanding!

**Comment by SaptarshiSarkar12** [comment]
> Thanks for understanding!

Welcome @anantnipunge 😄

**Comment by SaptarshiSarkar12** [comment]
If you are free, you may resume with the task. @anantnipunge

**Comment by anantnipunge** [comment]
Ok @SaptarshiSarkar12  Apologize for such a long delay. I will look into the website today and will update you.

**Comment by SaptarshiSarkar12** [comment]
> Ok @SaptarshiSarkar12 Apologize for such a long delay. I will look into the website today and will update you.

It's okay, take your time. Shall wait for your update, thank you :slightly_smiling_face: .

**Comment by anantnipunge** [comment]
> > hello @SaptarshiSarkar12 , shadow is removed but i'm unable to provide required feature to the all release section.
> > i think release section code is written somewhere else, i'm not getting that.
> 
> @anantnipunge Yes, the releases section code is written in script.js file starting from line 161. Please check if you can make the `All releases` section just like `Learn More` text.

hello @SaptarshiSarkar12 i'm back to project. 
i'm facing bit difficulties and errors about this section. but i think i can do it by resolving errors, just need some time till tomorrow night. if it is not possible from me i will update you and i will work on the new feature/ issue.

**Comment by SaptarshiSarkar12** [comment]
> > > hello @SaptarshiSarkar12 , shadow is removed but i'm unable to provide required feature to the all release section.
> > > i think release section code is written somewhere else, i'm not getting that.
> > 
> > 
> > @anantnipunge Yes, the releases section code is written in script.js file starting from line 161. Please check if you can make the `All releases` section just like `Learn More` text.
> 
> hello @SaptarshiSarkar12 i'm back to project. i'm facing bit difficulties and errors about this section. but i think i can do it by resolving errors, just need some time till tomorrow night. if it is not possible from me i will update you and i will work on the new feature/ issue.

Okay, @anantnipunge you can take your time.

**Comment by anantnipunge** [comment]
@SaptarshiSarkar12 i'm facing issue here: can't resolve it. tried all the way but no success.😥
image
Screenshot (212)

**Comment by anantnipunge** [comment]
can you help me or should i work on another issue?

**Comment by SaptarshiSarkar12** [comment]
> can you help me or should i work on another issue?

@anantnipunge I am a bit busy now, leave this for now. Work on making the different pages for each nav elements. Make sure that you remove all unnecessary CSS from each of the CSS files.

**Comment by anantnipunge** [comment]
Ok exactly i was thinking abt this 😊. Will ipdate soon.

**Comment by SaptarshiSarkar12** [comment]
> Ok exactly i was thinking abt this blush. Will ipdate soon.
> 
> @SaptarshiSarkar12 if you don't mind. can we have general discussion on discord?

Yeah, sure @anantnipunge .

**Comment by anantnipunge** [comment]
> > Ok exactly i was thinking abt this blush. Will ipdate soon.
> > 
> > @SaptarshiSarkar12 if you don't mind. can we have general discussion on discord?
> 
> Yeah, sure @anantnipunge .

Ok 😇

**Comment by SaptarshiSarkar12** [comment]
@anantnipunge How much work is done? Have you removed unnecessary CSS lines from the files? Have you faced any problem? Feel free to share, shall try to help.

**Comment by SaptarshiSarkar12** [comment]
> Ok exactly i was thinking abt this 😊. Will ipdate soon.
> 
> @SaptarshiSarkar12 if you don't mind. can we have general discussion on discord?

@anantnipunge Have you removed unnecessary CSS lines from the files? Has the task been completed? If you have any problem, let me know.

**Comment by SaptarshiSarkar12** [comment]
Closing this due to inactivity. Moreover, the website is going to be revamped via #196 , so this PR is no more required.

**Pull request closed without merging**
