### PR TITLE
added shadows to the buttons to look more immersive

### PR DESCRIPTION
**Pull request by Ansh1Mondal**

### CODE REVIEW

**Comment by SaptarshiSarkar12** [comment]
@Ansh1Mondal Your changes look good, please create an issue and link that with this PR.

**Comment by Ansh1Mondal** [comment]
ya sure

**Comment by Ansh1Mondal** [comment]
will you merge this PR ?

**Comment by SaptarshiSarkar12** [comment]
> will you merge this PR ?

Fiest let me review it @Ansh1Mondal .

**Comment by Ansh1Mondal** [comment]
ok sure

**Review by SaptarshiSarkar12 — APPROVED** [review]
LGTM 👍. Thanks for contributing 🚀 🚀 
@Ansh1Mondal **please leave a star on this project if you liked contributing to it.**

**Pull request merged**
