### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by sharvit18**
The website already has more information of the product Drifty then I think it should not have the about section

### CODE REVIEW

**Comment by Luciferr-18** [comment]
The required information about it has already been displayed in the home and the contribute section so I think it should not have the about section

**Comment by SaptarshiSarkar12** [comment]
@Luciferr-18 it is already in progress. Check #128

**Comment by SaptarshiSarkar12** [comment]
Ypu may modify that after it is merged or may contribute to any other part of the project. @Luciferr-18

**Comment by SaptarshiSarkar12** [comment]
> The required information about it has already been displayed in the home and the contribute section so I think it should not have the about section

It will contain my GitHub readme along with my avatar. @Luciferr-18

**Comment by Luciferr-18** [comment]
>

**Comment by Luciferr-18** [comment]
what if we add a new div in which it would countain you github redme page and avatar?@

> > The required information about it has already been displayed in the home and the contribute section so I think it should not have the about section
> 
> It will contain my GitHub readme along with my avatar. @Luciferr-18

**Comment by SaptarshiSarkar12** [comment]
> what if we add a new div in which it would countain you github redme page and avatar?
> 
> > > The required information about it has already been displayed in the home and the contribute section so I think it should not have the about section
> > 
> > 
> > It will contain my GitHub readme along with my avatar. @Luciferr-18

Do you want to create a new page within the website ? Or a new section? @Luciferr-18

**Comment by Luciferr-18** [comment]
> > what if we add a new div in which it would countain you github redme page and avatar?
> > > > The required information about it has already been displayed in the home and the contribute section so I think it should not have the about section
> > > 
> > > 
> > > It will contain my GitHub readme along with my avatar. @Luciferr-18
> 
> Do you want to create a new page within the website ? Or a new section? @Luciferr-18
we can have either  of them which will contain littile bit of text about how you came with the idea etc. and your github and your avatar

**Comment by SaptarshiSarkar12** [comment]
That's a great idea @Luciferr-18 !
I am assigning you in #127 as @Kamlesh72 will not work on the issue. I am also linking this PR to #127 , please make the changes and let me know when you are done. I shall review it.

**Comment by SaptarshiSarkar12** [comment]
Please leave a comment in #127 so that I can assign you. @Luciferr-18

**Comment by SaptarshiSarkar12** [comment]
> > > what if we add a new div in which it would countain you github redme page and avatar?
> > > > > The required information about it has already been displayed in the home and the contribute section so I think it should not have the about section
> > > > 
> > > > 
> > > > It will contain my GitHub readme along with my avatar. @Luciferr-18
> > 
> > 
> > Do you want to create a new page within the website ? Or a new section? @Luciferr-18
> 
> we can have either of them which will contain littile bit of text about how you came with the idea etc. and your github and your avatar

Please make the changes and let me know when you are done @Luciferr-18 .

**Comment by SaptarshiSarkar12** [comment]
> > > what if we add a new div in which it would countain you github redme page and avatar?
> > > > > The required information about it has already been displayed in the home and the contribute section so I think it should not have the about section
> > > > 
> > > > 
> > > > It will contain my GitHub readme along with my avatar. @Luciferr-18
> > 
> > 
> > Do you want to create a new page within the website ? Or a new section? @Luciferr-18
> 
> we can have either of them which will contain littile bit of text about how you came with the idea etc. and your github and your avatar

How much is completed ? @sharvit18

**Pull request closed without merging**
