### PR TITLE
Added required markdown files, rendered them in nextjs.

### LINKED ISSUE #273: [FEATURE] Add docs for the Website
### Is your feature request related to a problem? Please describe.

The README file currently lacks examples and use cases for both Drifty CLI and GUI. It also does not mention the custom issue labels that the project uses. 
Before testing their changes, the contributors need to run some commands. The addition of Dockerfiles to this project via #218 will require some notes and advices, but the README file is already too crowded and lengthy.

### Describe the solution you'd like.

I would like to have a docs section for Drifty with sections like - **Quickstart**, **Getting Started**, **Contributing**, **FAQ** and **Troubleshooting**.
- **Quickstart**: A brief introduction to the main features of Drifty, with a simple example to get users up and running in minutes.
- **Getting Started**: A more detailed guide on how to install, configure, and use Drifty, with explanations of the core components and options.
- **Contributing**: A section for developers who want to help make Drifty better, with instructions on how to set up a development environment, submit pull requests, and report bugs and new ideas.
- **FAQ**: A collection of common questions and answers about Drifty, covering topics such as compatibility, performance, security, and customization.
- **Troubleshooting**: This subsection helps to resolve common issues and errors that users may encounter while using Drifty and suggests possible solutions and workarounds.

The docs should be in **markdown files** and will be rendered by next js. You can read more about this [here](https://nextjs.org/docs/app/building-your-application/configuring/mdx).
> If you have any suggestions to add more suggestions, please let me know.

### Screenshots

The docs page can have a look like this -

Image

> You can see the live version of the docs homepage [here](https://drifty-git-preview-docs-saptarshisarkar12.vercel.app/docs).

### Additional information
*Skills you need to solve this issue* - **NextJS**, **TailwindCSS**, [**MD / MDX in Nextjs**](https://nextjs.org/docs/app/building-your-application/configuring/mdx).
Those who wish to work on this issue, please leave a comment below and I will assign you with the task.

### PR DESCRIPTION
**Pull request by markandey1414**
## Fixes issue

Fixes #273 

## Changes proposed

1. I added 5 markdown files namely quickstart.md, getting-started.md, troubleshooting.md, faq.md and header.md.
2. Next, I added `next.config.js` that enables MDX support.
3. Added `rermark-html.js` that transforms markdown files into HTML using remark.
4. Added `api.js` inside a new folder `lib/` to fetch the markdown files from the components folder and convert them into HTML.
5. Lastly, added `index.js` inside `pages/docs/` that renders the documentation.

## Check List (Check all the applicable boxes) 
- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

image
image
image

## Note to reviewers

I was not able to run the project locally due to issues with my local machine. However, the changes might be significant for the further development of the project.

### CODE REVIEW

**Review by SaptarshiSarkar12 — CHANGES_REQUESTED** [review]
@markandey1414 You have made docs pages for Next js with pages but the website uses **Next JS 13 with _*app*_ router**. Please make the necessary changes to make your code compatible with app router.

**Comment by markandey1414** [comment]
@SaptarshiSarkar12 yes sure, on it 👍

**Comment by SaptarshiSarkar12** [comment]
@markandey1414 Can you please delete the **packages** published on your fork repo? You can read more [here](https://docs.github.com/en/packages/learn-github-packages/deleting-and-restoring-a-package#deleting-an-entire-repository-scoped-package-on-github) to know how to delete an entire package.

**Comment by markandey1414** [comment]
@SaptarshiSarkar12 yes deleted

**Comment by SaptarshiSarkar12** [comment]
Thank you @markandey1414.
@markandey1414 How much is done? Also, I think that you are making changes in the project root, but, the website source code is present in the **Website** directory. Please make changes there.

**Comment by markandey1414** [comment]
@SaptarshiSarkar12 Yes. I've been trying to wrap my head around this, have issues working with app router.

**Comment by markandey1414** [comment]
@SaptarshiSarkar12 Yes, I checked and added the required code. Have a look.

**Comment by SaptarshiSarkar12** [comment]
@markandey1414 Please resolve the deployment failures.

**Comment by SaptarshiSarkar12** [comment]
@markandey1414 Here are the deployment logs provided by Vercel.
```bash
[22:08:18.814] ./app/docs/doc.js
[22:08:18.814] 19:22  Error: Do not pass children as props. Instead, nest children between the opening and closing tags.  react/no-children-prop
[22:08:18.814] 22:24  Error: Do not pass children as props. Instead, nest children between the opening and closing tags.  react/no-children-prop
[22:08:18.815] 23:24  Error: Do not pass children as props. Instead, nest children between the opening and closing tags.  react/no-children-prop
[22:08:18.815] 24:24  Error: Do not pass children as props. Instead, nest children between the opening and closing tags.  react/no-children-prop
[22:08:18.815] 25:24  Error: Do not pass children as props. Instead, nest children between the opening and closing tags.  react/no-children-prop
[22:08:18.815] 
[22:08:18.815] info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
[22:08:18.845] Error: Command "npm run build" exited with 1
```

**Comment by SaptarshiSarkar12** [comment]
The index page (the main page) of docs should be named **page.js**. I think you need to rename **docs.js** to **page.js**.

**Comment by markandey1414** [comment]
@SaptarshiSarkar12 but wouldn't that lead to conflict? I've added it similar to `about` page. 
image

**Comment by SaptarshiSarkar12** [comment]
@markandey1414 No, as the **page.js** file will be present in **docs** directory.

**Comment by SaptarshiSarkar12** [comment]
@markandey1414 Please fix the deployment failure. The logs from Vercel are -
```bash
[22:39:12.800] Failed to compile.
[22:39:12.801] 
[22:39:12.801] ./app/docs/page.js
[22:39:12.801] ReactServerComponentsError:
[22:39:12.801] 
[22:39:12.801] You have a Server Component that imports next/router. Use next/navigation instead.
[22:39:12.801] Learn more: https://nextjs.org/docs/app/api-reference/functions/use-router
[22:39:12.801] 
[22:39:12.801] Import trace:
[22:39:12.801]   ./app/docs/page.js
[22:39:12.801] 
[22:39:12.802] 
[22:39:12.802] > Build failed because of webpack errors
[22:39:12.827] Error: Command "npm run build" exited with 1
```

**Comment by SaptarshiSarkar12** [comment]
@markandey1414 Please fix the deployment failure. Here are the logs from Vercel.
```bash
[22:47:33.859] Failed to compile.
[22:47:33.859] 
[22:47:33.860] ./app/docs/page.js
[22:47:33.860] ReactServerComponentsError:
[22:47:33.860] 
[22:47:33.860] "getStaticProps" is not supported in app/. Read more: https://nextjs.org/docs/app/building-your-application/data-fetching
[22:47:33.860] 
[22:47:33.860]     ,-[[36;1;4m/vercel/path0/Website/app/docs/page.js[0m:23:1]
[22:47:33.860]  [2m23[0m |   )
[22:47:33.860]  [2m24[0m | }
[22:47:33.860]  [2m25[0m | 
[22:47:33.860]  [2m26[0m | export async function getStaticProps() {
[22:47:33.860]     : [31;1m                      ^^^^^^^^^^^^^^[0m
[22:47:33.860]  [2m27[0m |   const headerHtml = await getComponentHtml('header')
[22:47:33.860]  [2m28[0m |   const quickstartHtml = await getComponentHtml('quickstart')
[22:47:33.861]  [2m29[0m |   const gettingStartedHtml = await getComponentHtml('getting-started')
[22:47:33.861]     `----
[22:47:33.861] 
[22:47:33.861] File path:
[22:47:33.861]   ./app/docs/page.js
[22:47:33.861] 
[22:47:33.861] 
[22:47:33.861] > Build failed because of webpack errors
[22:47:33.885] Error: Command "npm run build" exited with 1
```

**Comment by markandey1414** [comment]
@SaptarshiSarkar12 can you please show me the latest logs? I'm not able to sign into vercel

**Comment by SaptarshiSarkar12** [comment]
Here's the latest logs.
```bash
[22:49:23.768]    Creating an optimized production build ...
[22:49:26.047] Failed to compile.
[22:49:26.047] 
[22:49:26.047] ./app/docs/page.js
[22:49:26.047] ReactServerComponentsError:
[22:49:26.047] 
[22:49:26.047] "getStaticProps" is not supported in app/. Read more: https://nextjs.org/docs/app/building-your-application/data-fetching
[22:49:26.047] 
[22:49:26.048]     ,-[[36;1;4m/vercel/path0/Website/app/docs/page.js[0m:23:1]
[22:49:26.048]  [2m23[0m |   )
[22:49:26.048]  [2m24[0m | }
[22:49:26.048]  [2m25[0m | 
[22:49:26.048]  [2m26[0m | export async function getStaticProps() {
[22:49:26.048]     : [31;1m                      ^^^^^^^^^^^^^^[0m
[22:49:26.048]  [2m27[0m |   const headerHtml = await getComponentHtml('header')
[22:49:26.048]  [2m28[0m |   const quickstartHtml = await getComponentHtml('quickstart')
[22:49:26.048]  [2m29[0m |   const gettingStartedHtml = await getComponentHtml('getting-started')
[22:49:26.048]     `----
[22:49:26.048] 
[22:49:26.048] File path:
[22:49:26.048]   ./app/docs/page.js
[22:49:26.048] 
[22:49:26.049] 
[22:49:26.049] > Build failed because of webpack errors
[22:49:26.072] Error: Command "npm run build" exited with 1
```

**Comment by SaptarshiSarkar12** [comment]
@markandey1414 I have disabled **Log protection**. So, you can check the logs and find what is the reason for the error and applying the required fix.

**Comment by SaptarshiSarkar12** [comment]
You do not require to login now.

**Comment by SaptarshiSarkar12** [comment]
@markandey1414 Try running `npm i react-markdown` in the **Website** directory and then, commit the changes. The error will get resolved.

**Comment by markandey1414** [comment]
@SaptarshiSarkar12 I'll be going further with this issue, will resolve it 👍

**Comment by markandey1414** [comment]
> @markandey1414 Try running `npm i react-markdown` in the **Website** directory and then, commit the changes. The error will get resolved.

its there already, I've just added it in gitignore

**Comment by SaptarshiSarkar12** [comment]
Okay @markandey1414

**Comment by SaptarshiSarkar12** [comment]
> > @markandey1414 Try running `npm i react-markdown` in the **Website** directory and then, commit the changes. The error will get resolved.
> 
> its there already, I've just added it in gitignore

@markandey1414 Please remove any changes that you have made in `.gitignore` file. **Node Modules** are already added in gitignore file present in the **Wesbite** directory.

**Comment by SaptarshiSarkar12** [comment]
@markandey1414 Were you able to understand the reason for the build failure? I think you have not added `react-markdown` in your package.json file. Also, the `lib/api.js` file no longer exists. So, you need to fix these issues to have a successful deployment.

**Comment by markandey1414** [comment]
> @markandey1414 Were you able to understand the reason for the build failure? I think you have not added `react-markdown` in your package.json file. Also, the `lib/api.js` file no longer exists. So, you need to fix these issues to have a successful deployment.

yes I did understand the issues with docs/page.js. But the file api.js is still there, I guess there's no issue with that.

**Comment by markandey1414** [comment]
@SaptarshiSarkar12 I'm facing an issue while pushing changes. I even added node modules to gitignore and did all I could think, yet I'm repeatedly getting this issue.
image

**Comment by SaptarshiSarkar12** [comment]
@markandey1414 Please don't push. I think you are trying to push the `node_modules` directory which is not good. So, let me fix the error. Then, everything should work fine on your end also. I am trying to fix the lib and gitignore files.

**Comment by markandey1414** [comment]
yes sure, I tried the pull command yet no changes.

**Comment by SaptarshiSarkar12** [comment]
Ok. Thank you

**Comment by SaptarshiSarkar12** [comment]
@markandey1414 You can now start working on the docs page. Some part of the **api.js** file is not correct, for which the build is failing. Please resolve that issue. Also, the docs page will not be single page. It will have multiple sections and sub-sections, so, please try to make it accordingly.

**Comment by SaptarshiSarkar12** [comment]
@markandey1414 Did you face any problem after I have pushed my changes?

**Comment by markandey1414** [comment]
@SaptarshiSarkar12 I tried multiple times, but it has been the same issue over and over again

**Comment by SaptarshiSarkar12** [comment]
@markandey1414 You can see [this tutorial on how to use MDX for next js website](https://www.youtube.com/watch?v=pqmij7wTgqc) and try re-creating the docs section again. Please use MDX as said in that video. It works.

**Comment by SaptarshiSarkar12** [comment]
@markandey1414 Are you able to solve this issue? Have you seen the resource I have shared earlier?

**Comment by SaptarshiSarkar12** [comment]
@markandey1414 Please resolve the branch conflicts

**Comment by SaptarshiSarkar12** [comment]
@markandey1414 Please respond.

**Comment by SaptarshiSarkar12** [comment]
@markandey1414 Do you still wish to work on it? I shall close this PR as you have been inactive for a long time.

**Comment by markandey1414** [comment]
Hello @SaptarshiSarkar12, apologies for late response and all the trouble. I would like to withdraw this pr as I'm not able to solve the issue for a long time.

**Comment by SaptarshiSarkar12** [comment]
It's okay. Thank you for the response 🙂. I am closing this PR.

**Pull request closed without merging**
