### PR TITLE
Informative footer added with the external links

### PR DESCRIPTION
**Pull request by anantnipunge**
here i have created footer. it looks like complete web application

before ::

image

after ::

image

**Note: still working on it to improve more.**

### CODE REVIEW

**Comment by anantnipunge** [comment]
please merge this PR. further if you want to improve more i'm here to do that.
nd please label it with hacktoberfest.

**Comment by anantnipunge** [comment]
this solves issue #155

**Comment by SaptarshiSarkar12** [comment]
@anantnipunge Please make the color look more distinct in dark mode.
image

**Comment by anantnipunge** [comment]
footer updated everything works very well. you can check. 

now :: **in dark mode**

image

**in light mode**

image
.
.
.
.
.
please merge this PR now. then,  if you want update anything please tell me, i love working on your project.

**Comment by anantnipunge** [comment]
please merge this PR.

**Comment by SaptarshiSarkar12** [comment]
@anantnipunge please fix this for mobiles.
Screenshot_2022-10-26-00-00-26

**Comment by anantnipunge** [comment]
Ya sure i will.

**Comment by SaptarshiSarkar12** [comment]
> Ya sure i will.

Ok @anantnipunge .

**Comment by SaptarshiSarkar12** [comment]
@anantnipunge what should I keep in privacy policy, terms and conditions and secuirity? Any idea?
Also, can you keep any other name instead of career?

**Comment by anantnipunge** [comment]
can you please suggest. i'm unable to think about this. because, i think it's up to you what should we add in privacy polilcy and t & c

**Comment by SaptarshiSarkar12** [comment]
> can you please suggest. i'm unable to think about this. because, i think it's up to you what should we add in privacy polilcy and t & c

Ok let me see, need to think on this.

@anantnipunge Can you think of any other name instead of `Career`

**Comment by anantnipunge** [comment]
optional to Career:

1. general -->
2.  about -->
3.  Learn --> get in touch + community + blog + resourses
4. Success stories -->

what do you think??

**Comment by SaptarshiSarkar12** [comment]
> optional to Career:
> 
> 1. general -->
> 2. about -->
> 3. Learn --> get in touch + community + blog + resourses
> 4. Success stories -->
> 
> what do you think??

Do one thing, remove the contact us section.
Add the footer as the contact us , and change career to support.
Also add the link to community as https://discord.gg/DeT4jXPfkG

**Comment by SaptarshiSarkar12** [comment]
@anantnipunge

**Comment by anantnipunge** [comment]
ok sure @SaptarshiSarkar12

**Comment by anantnipunge** [comment]
image


look here is it okay??

**Comment by anantnipunge** [comment]
@SaptarshiSarkar12

**Comment by SaptarshiSarkar12** [comment]
> image
> 
> look here is it okay??

Keep some padding in the right side of community and get in touch. @anantnipunge

**Comment by anantnipunge** [comment]
ya ok.

**Comment by anantnipunge** [comment]
you can check now:

image

**Comment by anantnipunge** [comment]
discord link added to community

**Comment by anantnipunge** [comment]
**changed name in legals**
this looks good or previous one .what do you think ??  

image

**Comment by SaptarshiSarkar12** [comment]
> **shortened items name in legals. code is not changed yet, just asking.** this looks good or previous one .what do you think ??
> 
> image
> 
> image

Yup, it looks better @anantnipunge

**Comment by SaptarshiSarkar12** [comment]
You have made some unnecessary changes also, please revert. @anantnipunge 
image

**Comment by anantnipunge** [comment]
Ok i will change it

**Comment by SaptarshiSarkar12** [comment]
> Ok i will change it

**Comment by SaptarshiSarkar12** [comment]
Sorry, closed it by mistake. @anantnipunge

**Comment by SaptarshiSarkar12** [comment]
> see i have made totally responsive now. please merge this PR. @SaptarshiSarkar12

@anantnipunge please add link to the `license` file in the repo to `Terms` button. I shall add secuirity file in the repo soon and then , shall re-review this PR.

**Comment by anantnipunge** [comment]
license file added to the terms

**Comment by SaptarshiSarkar12** [comment]
Please keep this parts as it is now. @anantnipunge 
Screenshot_2022-10-26-22-41-04
Screenshot_2022-10-26-22-40-57

**Comment by SaptarshiSarkar12** [comment]
Please keep this parts as it is now. @anantnipunge 
Screenshot_2022-10-26-22-41-04
Screenshot_2022-10-26-22-40-57

## Keep it like this - 
Screenshot_2022-10-26-23-12-50
Screenshot_2022-10-26-23-12-37

**Comment by anantnipunge** [comment]
it already as it was
nothing changed in this part.

**Comment by anantnipunge** [comment]
please merge this PR. further i will continue updating code according to you.

**Comment by SaptarshiSarkar12** [comment]
Ok, please make the changes requested as soon as possible.

**Comment by anantnipunge** [comment]
ok i will make it for sure.

**Comment by anantnipunge** [comment]
please tell me again where should i make changes.

**Comment by SaptarshiSarkar12** [comment]
> please tell me again where should i make changes.

I have already mentioned [here](https://github.com/SaptarshiSarkar12/Drifty/pull/160#issuecomment-1292392431). @anantnipunge

**Comment by anantnipunge** [comment]
hello i have created the issue #164. please assign me this issue. do check please and add hacktoberfest label.

**Comment by anantnipunge** [comment]
@SaptarshiSarkar12

**Comment by SaptarshiSarkar12** [comment]
Sure @anantnipunge

**Pull request merged**
