### PR TITLE
feat: Revamp the website with modern design

### LINKED ISSUE #720: [FEATURE] Revamp the website with modern design
### Is your feature request related to a problem? Please describe.

The website uses bad web practices and looks old and outdated.

### Describe the solution you'd like.

Bad practices: Using grid, padding and margin to separate elements instead of flex.
I replaced the incorrectly used padding and margin with flex and gap. 
PD: the grid is more difficult and not necessary in these cases.

Bug: Main section image animation shows scrollbar on X axis.
Fix: Overflow hidden in container div .

From antique buttons and anchors to modern and clean designs. Borderless, better border radius, more correct size, etc.

Minor changes in Footer. Minor changes in Demo section.

These changes improve consistency across the website.

### Home section:
With 2 buttons in header on hover:
image

### Contribute section:
With 2 buttons in header, 3 contributors avatar and fork button on hover:
image

### Demo section:
Normal:
image

Buttons on hover:
image

### Footer:
image

### Do you want to work on this issue?

Yes

### PR DESCRIPTION
**Pull request by FabrizioJordan**
## Fixes issue

Fixes #720

## Changes proposed

These changes improve consistency across the website.

## Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### Home section:
With 2 buttons in header on hover:
image

### Contribute section:
With 2 buttons in header, 3 contributors avatar and fork button on hover:
image

### Demo section:
Normal:
image

Buttons on hover:
image

### Footer:
image

## Note to reviewers

@SaptarshiSarkar12 please check it.
I didn't touch the Releases page because I think an issue is needed for this page alone.

**New Features**

Incorrectly used padding and margin replaced with flex and gap.
Modern and clean designs for buttons and anchors.
Minor changes in Footer. Minor changes in Demo section.

Updated styling for a consistent visual experience.

**Bug Fixes**

Overflow hidden in Main section.

## Release Notes

- **New Features**
	- Enhanced layout and styling across various components including Header, Footer, Main Section, and Demo for improved user experience.
  
- **Improvements**
	- Updated flexbox layouts for better alignment and spacing.
	- Refined hover effects for buttons and links to enhance visual feedback.
	- Adjusted font sizes and background colors for better readability and aesthetics.

- **Bug Fixes**
	- Addressed minor styling inconsistencies for a more uniform appearance.

### CODE REVIEW

**Review by SaptarshiSarkar12 — CHANGES_REQUESTED** [review]
@FabrizioJordan The UI looks awesome now :clap:. Please accept the DCO by signing your commits. Here are my points on your changes :point_down:
1. The animation gets cut out in the left portion. Also, the animation no longer matches with the current version as Drifty executables no longer depends on Java runtime. So, it would be better if you either fix the "cut-out issue" or update the animation with the latest one. As we have both GUI and CLI now, either we need to make a card arrangement (with two tabs for CLI and GUI) showing the preview of the working app. Let me know your views on it.

    https://github.com/user-attachments/assets/88323079-0ccc-4c8c-98f0-70dca63a813e

2. Can the header button texts be made bold? I suppose it would look good and have a good amount of contrast, wouldn't it?
image

**Comment by FabrizioJordan** [comment]
@SaptarshiSarkar12 Thanks for your feedback! I wanted to explain a few things so you know where I’m coming from.

I’m mainly a web developer, so I don’t have much experience with Java or the differences between GUI and CLI tools. What I did with the animation was just a quick fix by adding overflow-hidden to the parent container to stop it from overflowing. I didn’t know the animation was outdated or didn’t match the current project.

That said, I’ve now managed to apply the overflow-hidden in a different way, and the animation no longer gets cut on the left side. If this works for you, let me know, and I’ll adjust the PR to include it. If the animation still needs to be updated or changed, feel free to share the latest version, and I’ll be happy to apply it. Otherwise, I can leave it as is, and you or someone else can handle it later.

For the header (point #2), I already have some ideas to improve it for both Desktop and Mobile, and making the text bold is one of them.

Let me know what you think, and I’ll adjust the PR based on what’s needed.

**Comment by FabrizioJordan** [comment]
I also wanted to mention that I’ve been trying to follow the guidelines for the PR and signing the commits properly. I hope everything looks correct now, but if there’s anything I can improve, please let me know so I can fix it.

**Comment by SaptarshiSarkar12** [comment]
@FabrizioJordan Apologise for the late reply. I was busy in the weekend.

> I’m mainly a web developer, so I don’t have much experience with Java or the differences between GUI and CLI tools. What I did with the animation was just a quick fix by adding overflow-hidden to the parent container to stop it from overflowing. I didn’t know the animation was outdated or didn’t match the current project.

Okay. No issue. We can keep this animation for now. But it still gets cut on the left side. Please check once.
image

> For the header (point https://github.com/SaptarshiSarkar12/Drifty/discussions/2), I already have some ideas to improve it for both Desktop and Mobile, and making the text bold is one of them.

Yeah, we can proceed with those modifications as well. Should you create a new issue for that?

**Comment by SaptarshiSarkar12** [comment]
> I also wanted to mention that I’ve been trying to follow the guidelines for the PR and signing the commits properly. I hope everything looks correct now, but if there’s anything I can improve, please let me know so I can fix it.

That's great :+1:. I think there's a problem in the signing of commits, I will check once. If it is a false positive, I would remove that rule.

**Comment by FabrizioJordan** [comment]
> Yeah, we can proceed with those modifications as well. Should you create a new issue for that?

Sure! Once I finish this PR, I'll create a new one for those changes.

---
> That's great 👍. I think there's a problem in the signing of commits, I will check once. If it is a false positive, I would remove that rule.

The error was on my side. I didn’t know that VSCode doesn’t sign my commits automatically.

---

> But it still gets cut on the left side. Please check once.

With the new changes in this PR, the animation is no longer being cut on the left side.

----

Also, I noticed that the current CSS linter error is from the latest commit in the project, not my commits, and the error still persists. Let me know if there’s anything I should do about it!

**Comment by SaptarshiSarkar12** [comment]
> > Yeah, we can proceed with those modifications as well. Should you create a new issue for that?
> 
> Is not necessary, i will make the changes right now.

@FabrizioJordan Okay, the current changes look nice :+1:.

> > That's great 👍. I think there's a problem in the signing of commits, I will check once. If it is a false positive, I would remove that rule.
> 
> The error was on my side. I didn’t know that VSCode doesn’t sign my commits automatically.

It's okay :smile:.

> > But it still gets cut on the left side. Please check once.
> 
> With the new changes in this PR, the animation is no longer being cut on the left side.
> 
> Also, I noticed that the current CSS linter error is from the latest commit in the project, not my commits, and the error still persists. Let me know if there’s anything I should do about it!

I applied the fix :smiley: using prettier.

**Review by SaptarshiSarkar12 — APPROVED** [review]
@FabrizioJordan **Looks good to merge 👍.** 
**Thanks for contributing 🚀 🚀.**
You may join our _Discord server_ - **https://discord.gg/DeT4jXPfkG** to get updates about the project.

**Comment by FabrizioJordan** [comment]
**@SaptarshiSarkar12 Thank you for merging! 🚀** 
I'm glad to have contributed and would be happy to help with the web in the future.

**Comment by SaptarshiSarkar12** [comment]
> **@SaptarshiSarkar12 Thank you for merging! 🚀**

Most Welcome Fabricio :smile:.

> I'm glad to have contributed and would be happy to help with the web in the future. (maybe download page)

@FabrizioJordan I loved collaborating with you on this PR :heart:. Would love to see your wonderful work on the download page :upside_down_face:.

**Pull request merged**
