### PR TITLE
footer links transition fixed

### LINKED ISSUE #58: [FEATURE] Navbar scroll
### Is your feature request related to a problem? Please describe.

When you click on a link in the navbar it makes a very abrupt jump to the selected element,

### Describe the solution you'd like.

I think it would look better if instead it made a vertical scroll until you reach that element.
If you agree with my proposal I can implement these changes to the project

### Application Version

v1.1.0

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Waxer59**
#58 As the nav scroll was fixed I have been checking what could be improved and I have fixed the transition of the footer links.

### CODE REVIEW

**Comment by SaptarshiSarkar12** [comment]
@Waxer59 Please deploy the website in your Repo

**Comment by Waxer59** [comment]
What do you mean?

**Comment by Waxer59** [comment]
Ok

**Comment by Waxer59** [comment]
I Will send you the link asap

**Comment by Waxer59** [comment]
https://waxer59.github.io/Drifty/Website/

**Comment by Waxer59** [comment]
there you have the link

**Review by SaptarshiSarkar12 — APPROVED** [review]
LGTM 👍 . Thanks for contributing 🚀 🚀 . Please create an issue and link that with this PR. Then I shall merge this PR.

**Comment by Waxer59** [comment]
#77

**Pull request merged**
