### PR TITLE
Fixed bugs, added new navbar, favicons and fixed demo video bug

### PR DESCRIPTION
**Pull request by Pargat-Dhanjal**
Closing issue #43 

I have added a new and better responsive navbar along with favicons on top of webpage. Fixed a few bugs: Button alignment bug and demo video bug

https://user-images.githubusercontent.com/54456304/194435626-5c449e00-3926-4fd9-bde3-1ff666543194.mp4

### CODE REVIEW

**Comment by SaptarshiSarkar12** [comment]
@Pargat-Dhanjal The video is not playing. Please check it once and leave a comment if it plays in your case.

**Comment by SaptarshiSarkar12** [comment]
@Pargat-Dhanjal Please resolve the branch conflicts.

**Comment by SaptarshiSarkar12** [comment]
> @Pargat-Dhanjal Please resolve the branch conflicts.

@Pargat-Dhanjal Please resolve it.

**Comment by Pargat-Dhanjal** [comment]
@SaptarshiSarkar12 sure

**Pull request closed without merging**
