### PR TITLE
Site change Commit.

### PR DESCRIPTION
**Pull request by aryan-upa**
There are some site changes, basically changing the look and feel of it.

### CODE REVIEW

**Comment by aryan-upa** [comment]
## Screenshots [ Major updates are in hover as well ]
ss1
ss2
ss3
ss4

**Comment by aryan-upa** [comment]
https://aryan-upa.github.io/Drifty/
you can see working link here.

**Comment by SaptarshiSarkar12** [comment]
@aryan-upa Please make some required changes here. The text is not visible in dark mode.
image

**Comment by SaptarshiSarkar12** [comment]
@aryan-upa Also you need to make a change over here. The icons are not properly visible. Please specify whether the below image is in light or dark mode.
image

**Comment by SaptarshiSarkar12** [comment]
Also, please fix this. "Demonstration" word gets cut when i resize the screen to a smaller size. And the video doesn't Autoplay.
image

**Comment by aryan-upa** [comment]
> @aryan-upa Also you need to make a change over here. The icons are not properly visible. Please specify whether the below image is in light or dark mode. image

this is in dark mode, I didn't actually changed anything there.

**Comment by SaptarshiSarkar12** [comment]
> > @aryan-upa Also you need to make a change over here. The icons are not properly visible. Please specify whether the below image is in light or dark mode. image
> 
> this is in dark mode, I didn't actually changed anything there.

Please change the footer background from white to black and in light mode, change it from black to white and please make those icons in the footer more prominent

**Comment by SaptarshiSarkar12** [comment]
@aryan-upa How much is completed?

**Comment by aryan-upa** [comment]
I am working on the dark mode colors.

**Comment by aryan-upa** [comment]
[aryan-upa.github.io/Drifty/](https://aryan-upa.github.io/Drifty/) responsive updates can be seen here. Pls, confirm.

**Comment by SaptarshiSarkar12** [comment]
> [aryan-upa.github.io/Drifty/](https://aryan-upa.github.io/Drifty/) responsive updates can be seen here. Pls, confirm.

The below parts need changes - - (Along with that, the video doesn't autoplay)
image

image

**Comment by SaptarshiSarkar12** [comment]
> > [aryan-upa.github.io/Drifty/](https://aryan-upa.github.io/Drifty/) responsive updates can be seen here. Pls, confirm.
> 
> The below parts need changes - - (Along with that, the video doesn't autoplay) image
> 
> image

@aryan-upa Please make the required changes.

**Comment by SaptarshiSarkar12** [comment]
> I am working on the dark mode, hopefully can confirm it's completion by evening.

Ok, then I'll review it after you complete it. Just leave a comment after you have completed it.

**Comment by SaptarshiSarkar12** [comment]
> I am working on the dark mode, hopefully can confirm it's completion by evening.

Still the video is not playing automatically.

**Comment by aryan-upa** [comment]
Resolved, website has new look and feel, dark mode is working and video is also playing. [aryan-upa.github.io/Drifty/](https://aryan-upa.github.io/Drifty/)

**Comment by SaptarshiSarkar12** [comment]
> Resolved, website has new look and feel, dark mode is working and video is also playing. [aryan-upa.github.io/Drifty/](https://aryan-upa.github.io/Drifty/)

Ok let me check

**Comment by SaptarshiSarkar12** [comment]
Please see if you can change "dark mode button" to "toggle button" if it looks good.
The toggle button can be like this - 

image

**Comment by SaptarshiSarkar12** [comment]
> Please see if you can change "dark mode button" to "toggle button" if it looks good. The toggle button can be like this -
> 
> image

@aryan-upa

**Comment by SaptarshiSarkar12** [comment]
@aryan-upa You can make the toggle button like this - https://blog.prototypr.io/create-a-scenic-day-and-night-toggle-button-with-html-and-css-37a8e2532e68. It is visually very appealing.

**Comment by SaptarshiSarkar12** [comment]
> @aryan-upa Please change the "dark mode button" to this - https://codepen.io/aliceyt/pen/eYpJobY

Please make the required changes, then , i shall review it.

**Comment by aryan-upa** [comment]
Although it looks cool, but don't you think it'll have it's own impact on site speed.

**Comment by aryan-upa** [comment]
all done.

**Pull request merged**
