### PR TITLE
Dark mode button UI improved.

### PR DESCRIPTION
**Pull request by bhumika-1-3**

### CODE REVIEW

**Comment by bhumika-1-3** [comment]
image

ISSUE:  BETTER UI FOR DARK MODE BUTTON

**Comment by SaptarshiSarkar12** [comment]
@bhumika-1-3 Can you please deploy these changes in your repo?

**Comment by bhumika-1-3** [comment]
I am unable to deploy the folder. Can you plz try.

**Comment by SaptarshiSarkar12** [comment]
> I am unable to deploy the folder. Can you plz try.

Please follow the later part of the discussions in this PR #74

**Comment by SaptarshiSarkar12** [comment]
> > I am unable to deploy the folder. Can you plz try.
> 
> Please follow the later part of the discussions in this PR #74

@bhumika-1-3

**Comment by bhumika-1-3** [comment]
I have deployed as instructed can you check ?  @SaptarshiSarkar12

**Comment by SaptarshiSarkar12** [comment]
@bhumika-1-3 You don't need to create "pages.yml", it's already present in your repo : https://github.com/bhumika-1-3/Drifty/blob/master/.github/workflows/pages.yml.

**Comment by SaptarshiSarkar12** [comment]
> @bhumika-1-3 You don't need to create "pages.yml", it's already present in your repo : https://github.com/bhumika-1-3/Drifty/blob/master/.github/workflows/pages.yml.

You just need to go to settings>pages>and then follow the below pic - 

image

**Comment by SaptarshiSarkar12** [comment]
> > @bhumika-1-3 You don't need to create "pages.yml", it's already present in your repo : https://github.com/bhumika-1-3/Drifty/blob/master/.github/workflows/pages.yml.
> 
> You just need to go to settings>pages>and then follow the below pic -
> 
> image

@bhumika-1-3 Then, your repo will be deployed at http://bhumika-1-3.github.io/Drifty

**Comment by bhumika-1-3** [comment]
image

only this is showing

**Comment by SaptarshiSarkar12** [comment]
> image
> 
> only this is showing

It's live at : https://bhumika-1-3.github.io/Drifty/

**Comment by SaptarshiSarkar12** [comment]
@bhumika-1-3 Please add the support of showing text - "Switch to Light Mode" when dark mode is enabled and vice versa.

Like this - 

image

**Comment by bhumika-1-3** [comment]
okay will do.

**Comment by bhumika-1-3** [comment]
image

image
 
@SaptarshiSarkar12

**Comment by bhumika-1-3** [comment]
image

image

@SaptarshiSarkar12

**Comment by SaptarshiSarkar12** [comment]
Nice @bhumika-1-3 !

**Review by SaptarshiSarkar12 — APPROVED** [review]
LGTM 👍. Thanks For Contributing 🚀 🚀

**Comment by SaptarshiSarkar12** [comment]
@bhumika-1-3 Please leave a star on my repo if you liked my project.

**Pull request merged**
