### PR TITLE
Implement Environment Variables for Maven and GraalVM Versions in Dockerfile

### LINKED ISSUE #401: Update Dockerfile to use environment variables for Maven and GraalVM versions
### Description

The versions of Maven and GraalVM in DockerFile are hardcoded. This approach is not flexible and requires manual updates in the Dockerfile each time we want to change the version of Maven or GraalVM. This change will improve the maintainability and flexibility of our Docker setup. It will make it easier to test our application with different versions of Maven and GraalVM, and will simplify the process of updating these tools in the future.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Surya-KN**
## Fixes issue

Fixes #401 

## Changes proposed

Modified the Dockerfile to use environment variables for the Maven and GraalVM versions. This allows for easy version updates by simply changing the environment variables, eliminating the need for Dockerfile modifications.

The changes in this pull request will enhance the maintainability of Docker setup and streamline the process of testing application with different versions of Maven and GraalVM.
## Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Summary by CodeRabbit

- **Chores**
	- Updated development environment setup with dynamic version specification for Maven and GraalVM.
	- Improved environment variables and installation paths for better toolchain management.

- **Documentation**
	- Provided a summary of the Dockerfile changes for setting up the development environment.

### CODE REVIEW

**Review by SaptarshiSarkar12 — CHANGES_REQUESTED** [review]
@Surya-KN The Maven download link does not get resolved. Please fix this issue.
image

**Comment by Surya-KN** [comment]
> @Surya-KN The Maven download link does not get resolved. Please fix this issue.
> image
> 

I have made the changes, check it out

**Comment by SaptarshiSarkar12** [comment]
@Surya-KN Still not working
image

**Comment by Surya-KN** [comment]
image
I have used args instead of env variables

**Review by SaptarshiSarkar12 — APPROVED** [review]
@Surya-KN **Looks good to merge 👍.** 
**Thanks for contributing 🚀 🚀.**
You may join our _Discord server_ - **https://discord.gg/DeT4jXPfkG** to get updates about the project.

**Comment by SaptarshiSarkar12** [comment]
> image I have used build args instead of env variables @SaptarshiSarkar12

Yeah, it's working now.
Thank you @Surya-KN :smile:!

**Pull request merged**
