### PR TITLE
Adding a contact page

### PR DESCRIPTION
**Pull request by IM-TECHNO**
Added Contact page #186

### CODE REVIEW

**Comment by IM-TECHNO** [comment]
Kindly Review @SaptarshiSarkar12

**Comment by IM-TECHNO** [comment]
Hello, Can you review ? @SaptarshiSarkar12

**Review by SaptarshiSarkar12 — CHANGES_REQUESTED** [review]
@IM-TECHNO Please fix this bug. 
**Bug Description -** When I enter only some inputs and some required inputs are missing, still the website shows _Thank you..._ . It should have shown *this is a required field* like in the second pic.

image
image

**Comment by IM-TECHNO** [comment]
Working on it @SaptarshiSarkar12

**Comment by SaptarshiSarkar12** [comment]
> Working on it @SaptarshiSarkar12

How much is done @IM-TECHNO ?

**Comment by SaptarshiSarkar12** [comment]
> > Working on it @SaptarshiSarkar12
> 
> How much is done @IM-TECHNO ?

@IM-TECHNO Please respond.

**Comment by IM-TECHNO** [comment]
i'm Working on it currently. I was busy for the past 2 days. Will Complete soon

**Comment by SaptarshiSarkar12** [comment]
> i'm Working on it currently. I was busy for the past 2 days. Will Complete soon

Ok, you may complete your work once you are free.

**Comment by IM-TECHNO** [comment]
Hello, I've been very busy lately and I apologize for the delay. I have disabled the message but made a workaround. I will update today.

**Comment by IM-TECHNO** [comment]
To test thanks.html, you might need to download the file as netlify doesn't change the internal URLs provided.

**Comment by IM-TECHNO** [comment]
@SaptarshiSarkar12 Kindly check when you're free.

**Comment by IM-TECHNO** [comment]
image
This change does not work when pushed to the web-server. I have tested it. This is because the _next value needs an URL and not a path. It is mentioned in it documentation.

**Comment by SaptarshiSarkar12** [comment]
@IM-TECHNO Please make the button background colour and `We'd love to hear from you` text colour more distinct and prominent in light mode.
image

**Comment by SaptarshiSarkar12** [comment]
> @IM-TECHNO Please make the button background colour and `We'd love to hear from you` text colour more distinct and prominent in light mode. image

Please make the above suggested changes and let me know when you are done. @IM-TECHNO I shall review it then.

**Comment by SaptarshiSarkar12** [comment]
@IM-TECHNO Have you completed the work?

**Comment by IM-TECHNO** [comment]
I apologize for the long delay. I wasn't well in these few days.  Covid never really leaves us lol. I have completed the asked works, kindly check and update.

**Comment by SaptarshiSarkar12** [comment]
> I apologize for the long delay. I wasn't well in these few days. Covid never really leaves us lol. I have completed the asked works, kindly check and update.

It's okay, get well soon and take some rest as well. I have checked your latest commits, everything seems fine. Shall review it shortly.

**Review by SaptarshiSarkar12 — APPROVED** [review]
Looks good to merge :+1: Thanks for contributing :rocket: :rocket: :rocket:

**Comment by IM-TECHNO** [comment]
I should thank you for not closing this issue for inactivity. I really liked the idea of Drifty and I still want to contribute more to the FrontEnd side !. Cheers !

**Comment by SaptarshiSarkar12** [comment]
> I should thank you for not closing this issue for inactivity. I really liked the idea of Drifty and I still want to contribute more to the FrontEnd side !. Cheers !

Thank you for your appreciation! I wait for every inactive contributors to respond before I take any important steps. Surely, you may work on other frontend ideas of this project as well. @IM-TECHNO

**Comment by IM-TECHNO** [comment]
I will contribute more to Drifty ! Thanks ! ❤️

**Comment by SaptarshiSarkar12** [comment]
> I will contribute more to Drifty ! Thanks ! ❤️

Welcome @IM-TECHNO

**Pull request merged**
