### PR TITLE
bug: Features section not properly arranged

### PR DESCRIPTION
**Pull request by iryanraushan**
## Fixes issue

_No issues found_

## Changes Proposed
Features section in the website has been re-arranged to same height and card gap has been made the same.

## Summary by CodeRabbit

- **Style**
  - Increased spacing between items in the Features section for better visual separation.
  - Improved alignment of feature items for enhanced visual consistency.

### CODE REVIEW

**Review by SaptarshiSarkar12 — CHANGES_REQUESTED** [review]
@iryanraushan For Galaxy Fold (280 x 653), the contents of the features section overflows. Please fix that.
**Before:**
image

**After:**
image

**Comment by iryanraushan** [comment]
Let me see

**Comment by iryanraushan** [comment]
is there any problem on my commit ?

**Comment by SaptarshiSarkar12** [comment]
@iryanraushan I am reviewing #349. This (#347) is the old PR, so, an `invalid` label has been added.

**Pull request closed without merging**
