### PR TITLE
add hover effect to cursor pointer

### PR DESCRIPTION
**Pull request by RyanRaushan**

### CODE REVIEW

**Comment by RyanRaushan** [comment]
updated the hover effect on download button

**Comment by SaptarshiSarkar12** [comment]
Website deploy preview link - https://deploy-preview-207--drifty.netlify.app/

**Comment by SaptarshiSarkar12** [comment]
@RyanRaushan I am out of station for a week. After I return home, I shall be a bit busy but once I get free, I shall review it.

**Review by SaptarshiSarkar12 — APPROVED** [review]
@RyanRaushan **Looks good to merge 👍.** 
**Thanks for contributing 🚀 🚀.**
You may join our _Discord server_ - **https://discord.gg/DeT4jXPfkG** to get updates about the project.

**Pull request merged**
