### PR TITLE
 footer 

### PR DESCRIPTION
**Pull request by frypan01**
#84

### CODE REVIEW

**Review by SaptarshiSarkar12 — COMMENTED** [review]
@frypan01 **The changes you have made might have led to the decline of performance in the website. Please try to fix this problem if possible and let me know after it has been fixed.**

### Before (Check here: https://pagespeed.web.dev/report?url=https%3A%2F%2Fsaptarshisarkar12.github.io%2FDrifty%2F&form_factor=mobile)
image
image


### After (Check here: https://pagespeed.web.dev/report?url=https%3A%2F%2Fdeploy-preview-129--drifty.netlify.app%2F&form_factor=mobile)
image
image

**Comment by SaptarshiSarkar12** [comment]
> Sir, I have just changed the colors in footer section and no other change or code is touched, majorly the Screenshot 2022-10-19 061008
> 
> But I am still trying , if I can do something!!

ok @frypan01, try if you can fix it.

**Comment by SaptarshiSarkar12** [comment]
Please resolve the conflicts @frypan01

**Comment by SaptarshiSarkar12** [comment]
@frypan01 Are you still working on it or are you interested in working on this pull request? If yes, you may create a new pull request as this PR contains merge conflicts. 
Else I may close this as well as the issue linked because of inactivity.

**Comment by SaptarshiSarkar12** [comment]
> @frypan01 Are you still working on it or are you interested in working on this pull request? If yes, you may create a new pull request as this PR contains merge conflicts. Else I may close this as well as the issue linked because of inactivity.

What about this @frypan01 ?

**Comment by frypan01** [comment]
Yeah, Please close

**Comment by SaptarshiSarkar12** [comment]
> Yeah, Please close

Ok closing this.

**Pull request closed without merging**
