### PR TITLE
padding to nav-bar items and 'download here' section

### PR DESCRIPTION
**Pull request by anantnipunge**
for issue #164 . i have set padding to the nav-bar items and download section. 

**before:**

image

image

**after:**

image

image

### CODE REVIEW

**Comment by anantnipunge** [comment]
please merge this PR @SaptarshiSarkar12 .
so that i could work on new part of the website. i think we need to think on `about` section because it's empty and also thinking about more features. i mean we need to research on it, then we can make it good.

**Review by SaptarshiSarkar12 — APPROVED** [review]
LGTM 👍. Thanks for contributing 🚀 🚀.  @anantnipunge Please leave a star ⭐ on this project if you liked it and haven't already.

**Comment by SaptarshiSarkar12** [comment]
> please merge this PR @SaptarshiSarkar12 . so that i could work on new part of the website. i think we need to think on `about` section because it's empty and also i'm thinking about more features. i mean we need to research on it, then we can make it good.

The about section is in progress, but @sharvit18 is not responding. Let me see for few more hours, if he doesn't respond, you may work on #127 (PR no. - #150) . @anantnipunge

**Comment by anantnipunge** [comment]
okay sure @SaptarshiSarkar12

**Comment by SaptarshiSarkar12** [comment]
> okay sure @SaptarshiSarkar12 , i'm available to contribute.

**Comment by SaptarshiSarkar12** [comment]
> okay sure @SaptarshiSarkar12 , i'm available to contribute.

@anantnipunge you may work on #127 as @sharvit18 has unassigned himself from the work. Just leave a comment in #127 and I will assign you if you want to work on it.

**Pull request merged**
