### PR TITLE
Fixed merge conflicts

### LINKED ISSUE #43: [FEATURE]  Improve the Website UI - Responsive
### Is your feature request related to a problem? Please describe.

I would like to work on the entire Website UI and improve it as you can see that there are many things which don't work on the website as well as the UI design is not upto the mark. The Website is not resposive as well as there are many responsive bugs.

### Describe the solution you'd like.

I would like to work on the entire website part as a sole developer to improve the application and provide a better user experince for the application. 

### Application Version

v1.1.0

### Screenshots

Screenshot 2022-10-04 at 2 59 02 AM
Screenshot 2022-10-04 at 2 58 54 AM
Screenshot 2022-10-04 at 2 57 13 AM

### Additional information

Would gladly contribute to this website as a part of hacktober fest and would love to contribute my share to open source applications.

### PR DESCRIPTION
**Pull request by Pargat-Dhanjal**
Closes #43 
I have added favicons and fixed the social links with new buttons. Everything looks great 👍

Screenshot 2022-10-07 at 3 22 19 PM

Screenshot 2022-10-07 at 3 22 42 PM

### CODE REVIEW

**Comment by SaptarshiSarkar12** [comment]
@Pargat-Dhanjal Please deploy it in your repo, so that I can review it faster.

**Comment by Pargat-Dhanjal** [comment]
@SaptarshiSarkar12 I am unable to deploy the branch as the index file is presnt inside the Website folder

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 I am unable to deploy the branch as the index file is presnt inside the Website folder. Can you help me with it?

@Pargat-Dhanjal Please provide the screenshot of pages section of the settings page of your repo.

**Comment by SaptarshiSarkar12** [comment]
> > @SaptarshiSarkar12 I am unable to deploy the branch as the index file is presnt inside the Website folder. Can you help me with it?
> 
> @Pargat-Dhanjal Please provide the screenshot of pages section of the settings page of your repo.

here is a direct link for that : https://github.com/Pargat-Dhanjal/Drifty/settings/pages

**Comment by Pargat-Dhanjal** [comment]
Screenshot 2022-10-07 at 4 18 42 PM

@SaptarshiSarkar12

**Comment by SaptarshiSarkar12** [comment]
> Screenshot 2022-10-07 at 4 18 42 PM
> 
> @SaptarshiSarkar12

Please change "deploy from branch" to "github-actions"

**Comment by Pargat-Dhanjal** [comment]
Screenshot 2022-10-07 at 4 23 26
@SaptarshiSarkar12

**Comment by Pargat-Dhanjal** [comment]
@SaptarshiSarkar12 is everthing fine? Cause I was unable to find a github pages workflow

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 is everthing fine? Cause I was unable to find a github pages workflow

Everything seems fine, but I don't know why it's not showing the index page. You can get the workflow file here - https://github.com/Pargat-Dhanjal/Drifty/blob/master/.github/workflows/pages.yml

**Comment by SaptarshiSarkar12** [comment]
> > @SaptarshiSarkar12 is everthing fine? Cause I was unable to find a github pages workflow
> 
> Everything seems fine, but I don't know why it's not showing the index page. You can get the workflow file here - https://github.com/Pargat-Dhanjal/Drifty/blob/master/.github/workflows/pages.yml

Yeah, it worked. It's live here : https://pargat-dhanjal.github.io/Drifty/ .
But, favicon of the website doesn't appear - 
image

**Comment by SaptarshiSarkar12** [comment]
> > > @SaptarshiSarkar12 is everthing fine? Cause I was unable to find a github pages workflow
> > 
> > 
> > Everything seems fine, but I don't know why it's not showing the index page. You can get the workflow file here - https://github.com/Pargat-Dhanjal/Drifty/blob/master/.github/workflows/pages.yml
> 
> Yeah, it worked. It's live here : https://pargat-dhanjal.github.io/Drifty/ . But, favicon of the website doesn't appear - image

@Pargat-Dhanjal Please fix this.

**Comment by Pargat-Dhanjal** [comment]
@SaptarshiSarkar12 On it 👍

**Comment by Pargat-Dhanjal** [comment]
@SaptarshiSarkar12 
Fixed it 👍
Loved working on this project! best of luck ⚡️
Screenshot 2022-10-07 at 4 45 32 PM

**Review by SaptarshiSarkar12 — APPROVED** [review]
LGTM 👍. Thanks for contributing 🚀 🚀

**Review by SaptarshiSarkar12 — CHANGES_REQUESTED** [review]
Please make this part a bit more bright. 

image

**Comment by SaptarshiSarkar12** [comment]
> Please make this part a bit more bright.
> 
> image

@Pargat-Dhanjal

**Comment by Pargat-Dhanjal** [comment]
@SaptarshiSarkar12 do you want the background to be bright or change button style?

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 do you want the background to be bright or change button style?

The text "help and support" needs to be bright such that the text is properly visible

**Comment by SaptarshiSarkar12** [comment]
> > @SaptarshiSarkar12 do you want the background to be bright or change button style?
> 
> The text "help and support" needs to be bright such that the text is properly visible

@Pargat-Dhanjal

**Comment by Pargat-Dhanjal** [comment]
@SaptarshiSarkar12 Fixed buttons which match the style and goes with both light and dark mode.

**Review by SaptarshiSarkar12 — APPROVED** [review]
LGTM 👍. Thanks for contributing 🚀 🚀

**Pull request merged**
