### PR TITLE
Changes to Hero and Navbar

### PR DESCRIPTION
**Pull request by SujalSamai**
- Added the Animation in Hero section in Mobile Layout, so that the page looks more interactive and consistent.
- Changed Navbar Links to uppercase so that it looks more readable in mobile layout
image

P.s. All the other changes, that was assigned to me, somebody else did it :)

### CODE REVIEW

**Comment by SaptarshiSarkar12** [comment]
.deploy

**Comment by SaptarshiSarkar12** [comment]
.deploy

**Comment by SaptarshiSarkar12** [comment]
.deploy

**Comment by SaptarshiSarkar12** [comment]
.deploy

**Comment by SaptarshiSarkar12** [comment]
.deploy

**Comment by SaptarshiSarkar12** [comment]
.deploy master

**Comment by SaptarshiSarkar12** [comment]
.deploy main

**Comment by SaptarshiSarkar12** [comment]
.deploy

**Comment by SaptarshiSarkar12** [comment]
.deploy

**Comment by SaptarshiSarkar12** [comment]
.deploy

**Comment by SaptarshiSarkar12** [comment]
.deploy main

**Comment by SaptarshiSarkar12** [comment]
.deploy master

**Comment by SaptarshiSarkar12** [comment]
.deploy

**Comment by SaptarshiSarkar12** [comment]
@SujalSamai There is some problem with the workflow. So, can you please deploy your changes in your repo? You can follow the steps provided in the last part of the discussion here: #74

**Comment by SaptarshiSarkar12** [comment]
@SujalSamai **Please resolve the conflicts.**

**Comment by SujalSamai** [comment]
I have resolved the conflicts

**Comment by SaptarshiSarkar12** [comment]
> I have resolved the conflicts

Please keep the light and dark mode button as before like this - 

image


Or, fix this button in place of the checkbox

**Comment by SujalSamai** [comment]
Please merge this one first, I'll raise another PR after making changes. Otherwise it's getting really messy, in my local repository.

**Comment by SaptarshiSarkar12** [comment]
> Please merge this one first, I'll raise another PR after making changes. Otherwise it's getting really messy, in my local repository.

@SujalSamai I have fixed that problem by replacing the checkbox with sun/moon image during dark/light mode enabled. So, you may not need to change that unless you want to modify it.

**Pull request merged**
